-- Dimension Tables
-- No foreign key dependencies

-- dim_player: 28 columns
CREATE TABLE IF NOT EXISTS dim_player (
    index INTEGER,
    player_first_name VARCHAR(200),
    player_last_name VARCHAR(200),
    player_full_name VARCHAR(200),
    player_id VARCHAR(20) PRIMARY KEY,
    player_primary_position VARCHAR(20),
    current_skill_rating INTEGER,
    player_hand TEXT,
    birth_year INTEGER,
    player_gender VARCHAR(20),
    highest_beer_league VARCHAR(500),
    player_rating_ly INTEGER,
    player_notes TEXT,
    player_leadership VARCHAR(20),
    player_norad VARCHAR(20),
    player_csaha TEXT,
    player_norad_primary_number TEXT,
    player_csah_primary_number TEXT,
    player_norad_current_team VARCHAR(100),
    player_csah_current_team TEXT,
    player_norad_current_team_id VARCHAR(20),
    player_csah_current_team_id TEXT,
    other_url TEXT,
    player_url TEXT,
    player_image VARCHAR(500),
    random_player_first_name VARCHAR(200),
    random_player_last_name VARCHAR(200),
    random_player_full_name VARCHAR(200)
);

-- dim_team: 15 columns
CREATE TABLE IF NOT EXISTS dim_team (
    index INTEGER,
    team_name VARCHAR(200),
    team_id VARCHAR(20) PRIMARY KEY,
    norad_team VARCHAR(20),
    csah_team VARCHAR(20),
    league_id VARCHAR(20),
    league VARCHAR(20),
    long_team_name VARCHAR(200),
    team_cd VARCHAR(20),
    team_color1 VARCHAR(20),
    team_color2 VARCHAR(20),
    team_color3 VARCHAR(20),
    team_color4 VARCHAR(20),
    team_logo TEXT,
    team_url TEXT
);

-- dim_schedule: 44 columns
CREATE TABLE IF NOT EXISTS dim_schedule (
    game_id INTEGER PRIMARY KEY,
    season INTEGER,
    season_id INTEGER,
    game_url TEXT,
    home_team_game_id VARCHAR(20),
    away_team_game_id VARCHAR(20),
    date DATE,
    game_time VARCHAR(20),
    home_team_name VARCHAR(200),
    away_team_name VARCHAR(200),
    home_team_id VARCHAR(20),
    away_team_id VARCHAR(20),
    head_to_head_id VARCHAR(20),
    game_type VARCHAR(20),
    playoff_round VARCHAR(100),
    last_period_type VARCHAR(20),
    period_length VARCHAR(20),
    ot_period_length VARCHAR(20),
    shootout_rounds INTEGER,
    home_total_goals INTEGER,
    away_total_goals INTEGER,
    home_team_period1_goals INTEGER,
    home_team_period2_goals INTEGER,
    home_team_period3_goals INTEGER,
    home_team_periodOT_goals INTEGER,
    away_team_period1_goals INTEGER,
    away_team_period2_goals INTEGER,
    away_team_period3_goals INTEGER,
    away_team_periodOT_goals INTEGER,
    home_team_seeding INTEGER,
    away_team_seeding INTEGER,
    home_team_w INTEGER,
    home_team_l INTEGER,
    home_team_t INTEGER,
    home_team_pts INTEGER,
    away_team_w INTEGER,
    away_team_l INTEGER,
    away_team_t INTEGER,
    away_team_pts INTEGER,
    video_id TEXT,
    video_start_time TEXT,
    video_end_time TEXT,
    video_title TEXT,
    video_url TEXT
);

