mindmap
  root((BenchSight<br/>317 Stats))
    Core Box Score
      goals
      assists
      points
      sog
      shots_missed
      shots_blocked
    Time on Ice
      toi_seconds
      toi_minutes
      shift_count
      avg_shift
      playing_toi_seconds
    Possession
      cf
      ca
      cf_pct
      ff
      fa
      ff_pct
    Plus/Minus
      plus_minus
      plus_minus_adj
      ev_plus_minus
      pp_plus_minus
    Faceoffs
      fo_wins
      fo_losses
      fo_pct
      fo_wins_oz
      fo_wins_nz
      fo_wins_dz
    Zone Transitions
      zone_entries
      zone_exits
      zone_entry_carry
      zone_entry_dump
      controlled_entries
    Turnovers
      giveaways
      takeaways
      turnovers_oz
      turnovers_nz
      turnovers_dz
    Expected Goals
      xg_for
      xg_against
      xg_diff
      xg_pct
      xg_per_shot
    Shot Danger
      shots_high_danger
      shots_medium_danger
      shots_low_danger
      scoring_chances
      shot_quality_avg
    Performance
      game_score
      game_score_per_60
      game_score_rating
      performance_index
      rating_performance_delta
    Advanced
      rush_shots
      breakaway_attempts
      odd_man_rushes
      pass_success_rate
      defensive_contribution
