#!/usr/bin/env python3
"""
Dashboard Environment Setup Helper

Helps set up the .env.local file for the dashboard with Supabase credentials.
This script will:
1. Read your Supabase URL from config
2. Help you get the anon key (you'll need to provide it)
3. Create the .env.local file for the dashboard
"""

import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from config.config_loader import get_config

def setup_dashboard_env():
    """Set up dashboard environment variables."""
    print("=" * 80)
    print("DASHBOARD ENVIRONMENT SETUP")
    print("=" * 80)
    print()
    
    # Load config
    try:
        config = get_config()
        if not config.is_configured:
            print("✗ Supabase credentials not configured in config/config_local.ini")
            return False
        
        supabase_url = config.supabase_url
        print(f"✓ Found Supabase URL: {supabase_url}")
        print()
    except Exception as e:
        print(f"✗ Failed to load config: {e}")
        return False
    
    # Check if .env.local already exists
    dashboard_dir = project_root / "ui" / "dashboard"
    env_file = dashboard_dir / ".env.local"
    
    if env_file.exists():
        print(f"⚠ .env.local already exists at: {env_file}")
        response = input("Overwrite? (y/n): ").strip().lower()
        if response != 'y':
            print("Cancelled.")
            return False
    
    # Get anon key
    print()
    print("To get your Supabase anon key:")
    print("  1. Go to: https://supabase.com/dashboard")
    print("  2. Select your project")
    print("  3. Go to Settings → API")
    print("  4. Copy the 'anon' or 'public' key")
    print()
    
    anon_key = input("Enter your Supabase anon key (or press Enter to skip): ").strip()
    
    if not anon_key:
        print()
        print("⚠ No anon key provided. Creating .env.local with URL only.")
        print("   You'll need to add the anon key manually.")
        print()
        anon_key = "YOUR_ANON_KEY_HERE"
    
    # Create .env.local
    env_content = f"""# Supabase Configuration
# Generated by setup_dashboard_env.py

NEXT_PUBLIC_SUPABASE_URL={supabase_url}
NEXT_PUBLIC_SUPABASE_ANON_KEY={anon_key}

# Optional: Service role key for server-side operations
# SUPABASE_SERVICE_ROLE_KEY=your-service-role-key

# Optional: For on-demand revalidation
# REVALIDATION_SECRET=your-secret-here
"""
    
    try:
        env_file.parent.mkdir(parents=True, exist_ok=True)
        env_file.write_text(env_content)
        print()
        print("=" * 80)
        print("✓ SUCCESS!")
        print("=" * 80)
        print()
        print(f"Created: {env_file}")
        print()
        print("Next steps:")
        print("  1. cd ui/dashboard")
        print("  2. npm install  (if not done already)")
        print("  3. npm run dev")
        print("  4. Open http://localhost:3000")
        print()
        
        if anon_key == "YOUR_ANON_KEY_HERE":
            print("⚠ Remember to update NEXT_PUBLIC_SUPABASE_ANON_KEY in .env.local")
            print("   with your actual anon key from Supabase dashboard.")
            print()
        
        return True
        
    except Exception as e:
        print(f"✗ Failed to create .env.local: {e}")
        return False

if __name__ == "__main__":
    success = setup_dashboard_env()
    sys.exit(0 if success else 1)
