-- ============================================================
-- BENCHSIGHT SCHEMA - AUTO-GENERATED FROM CSV FILES
-- Generated to match exact column structure of data files
-- ============================================================
--
-- This script creates the 12 core data tables with ALL columns
-- from the CSV files. It does NOT touch the logging tables
-- (log_etl_runs, log_errors, etc.) which should be created
-- separately using 02_CREATE_LOGGING_TABLES.sql
--
-- Run this in Supabase SQL Editor to create/recreate tables
-- ============================================================

-- Drop existing tables in reverse dependency order
DROP TABLE IF EXISTS fact_wowy CASCADE;
DROP TABLE IF EXISTS fact_h2h CASCADE;
DROP TABLE IF EXISTS fact_goalie_game_stats CASCADE;
DROP TABLE IF EXISTS fact_team_game_stats CASCADE;
DROP TABLE IF EXISTS fact_player_game_stats CASCADE;
DROP TABLE IF EXISTS fact_shifts_player CASCADE;
DROP TABLE IF EXISTS fact_events_player CASCADE;
DROP TABLE IF EXISTS fact_events CASCADE;
DROP TABLE IF EXISTS fact_shifts CASCADE;
DROP TABLE IF EXISTS dim_schedule CASCADE;
DROP TABLE IF EXISTS dim_team CASCADE;
DROP TABLE IF EXISTS dim_player CASCADE;

-- ============================================================
-- CREATE TABLES
-- ============================================================

-- dim_player: 28 columns
CREATE TABLE dim_player (
    index INTEGER,
    player_first_name TEXT,
    player_last_name TEXT,
    player_full_name TEXT,
    player_id TEXT PRIMARY KEY,
    player_primary_position TEXT,
    current_skill_rating INTEGER,
    player_hand DECIMAL,
    birth_year DECIMAL,
    player_gender TEXT,
    highest_beer_league TEXT,
    player_rating_ly INTEGER,
    player_notes DECIMAL,
    player_leadership TEXT,
    player_norad TEXT,
    player_csaha DECIMAL,
    player_norad_primary_number DECIMAL,
    player_csah_primary_number DECIMAL,
    player_norad_current_team TEXT,
    player_csah_current_team DECIMAL,
    player_norad_current_team_id TEXT,
    player_csah_current_team_id TEXT,
    other_url TEXT,
    player_url TEXT,
    player_image TEXT,
    random_player_first_name TEXT,
    random_player_last_name TEXT,
    random_player_full_name TEXT
);

-- dim_team: 15 columns
CREATE TABLE dim_team (
    index INTEGER,
    team_name TEXT,
    team_id TEXT PRIMARY KEY,
    norad_team TEXT,
    csah_team TEXT,
    league_id TEXT,
    league TEXT,
    long_team_name TEXT,
    team_cd TEXT,
    team_color1 TEXT,
    team_color2 TEXT,
    team_color3 TEXT,
    team_color4 TEXT,
    team_logo TEXT,
    team_url TEXT
);

-- dim_schedule: 44 columns
CREATE TABLE dim_schedule (
    game_id TEXT PRIMARY KEY,
    season INTEGER,
    season_id TEXT,
    game_url TEXT,
    home_team_game_id TEXT,
    away_team_game_id TEXT,
    date DATE,
    game_time TEXT,
    home_team_name TEXT,
    away_team_name TEXT,
    home_team_id TEXT,
    away_team_id TEXT,
    head_to_head_id TEXT,
    game_type TEXT,
    playoff_round TEXT,
    last_period_type TEXT,
    period_length TEXT,
    ot_period_length TEXT,
    shootout_rounds INTEGER,
    home_total_goals INTEGER,
    away_total_goals INTEGER,
    home_team_period1_goals DECIMAL,
    home_team_period2_goals DECIMAL,
    home_team_period3_goals DECIMAL,
    home_team_periodOT_goals DECIMAL,
    away_team_period1_goals DECIMAL,
    away_team_period2_goals DECIMAL,
    away_team_period3_goals DECIMAL,
    away_team_periodOT_goals DECIMAL,
    home_team_seeding DECIMAL,
    away_team_seeding DECIMAL,
    home_team_w INTEGER,
    home_team_l INTEGER,
    home_team_t INTEGER,
    home_team_pts INTEGER,
    away_team_w INTEGER,
    away_team_l INTEGER,
    away_team_t INTEGER,
    away_team_pts INTEGER,
    video_id TEXT,
    video_start_time DECIMAL,
    video_end_time DECIMAL,
    video_title DECIMAL,
    video_url TEXT
);

-- fact_shifts: 63 columns
CREATE TABLE fact_shifts (
    shift_key TEXT PRIMARY KEY,
    game_id TEXT,
    shift_index INTEGER,
    Period DECIMAL,
    shift_start_min DECIMAL,
    shift_start_sec DECIMAL,
    shift_end_min DECIMAL,
    shift_end_sec DECIMAL,
    shift_start_type TEXT,
    shift_stop_type TEXT,
    home_forward_1 DECIMAL,
    home_forward_2 DECIMAL,
    home_forward_3 DECIMAL,
    home_defense_1 DECIMAL,
    home_defense_2 DECIMAL,
    home_xtra DECIMAL,
    home_goalie DECIMAL,
    away_forward_1 DECIMAL,
    away_forward_2 DECIMAL,
    away_forward_3 DECIMAL,
    away_defense_1 DECIMAL,
    away_defense_2 DECIMAL,
    away_xtra DECIMAL,
    away_goalie DECIMAL,
    stoppage_time DECIMAL,
    home_ozone_start DECIMAL,
    home_ozone_end DECIMAL,
    home_dzone_start DECIMAL,
    home_dzone_end DECIMAL,
    home_nzone_start DECIMAL,
    home_nzone_end DECIMAL,
    home_team TEXT,
    away_team TEXT,
    shift_start_total_seconds DECIMAL,
    shift_end_total_seconds DECIMAL,
    shift_duration DECIMAL,
    home_team_strength DECIMAL,
    away_team_strength DECIMAL,
    home_team_en DECIMAL,
    away_team_en DECIMAL,
    home_team_pk DECIMAL,
    home_team_pp DECIMAL,
    away_team_pp DECIMAL,
    away_team_pk DECIMAL,
    situation TEXT,
    strength TEXT,
    home_goals DECIMAL,
    away_goals DECIMAL,
    home_team_plus DECIMAL,
    home_team_minus DECIMAL,
    away_team_plus DECIMAL,
    away_team_minus DECIMAL,
    period_start_total_running_seconds DECIMAL,
    running_video_time DECIMAL,
    shift_start_running_time DECIMAL,
    shift_end_running_time DECIMAL,
    strength_id TEXT,
    situation_id TEXT,
    shift_start_type_id TEXT,
    shift_stop_type_id TEXT,
    home_team_id TEXT,
    away_team_id TEXT,
    period_id TEXT
);
CREATE INDEX idx_fact_shifts_game_id ON fact_shifts(game_id);

-- fact_events: 54 columns
CREATE TABLE fact_events (
    event_key TEXT PRIMARY KEY,
    game_id TEXT,
    period DECIMAL,
    event_index DECIMAL,
    linked_event_index DECIMAL,
    sequence_index DECIMAL,
    play_index DECIMAL,
    event_type TEXT,
    tracking_event_index DECIMAL,
    event_start_min DECIMAL,
    event_start_sec DECIMAL,
    event_end_min DECIMAL,
    event_end_sec DECIMAL,
    role_abrev TEXT,
    event_team_zone TEXT,
    home_team_zone TEXT,
    away_team_zone TEXT,
    team_venue TEXT,
    team_venue_abv TEXT,
    side_of_puck TEXT,
    play_detail1 TEXT,
    play_detail_2 TEXT,
    play_detail_successful TEXT,
    pressured_pressurer DECIMAL,
    zone_change_index DECIMAL,
    home_team TEXT,
    away_team TEXT,
    Type TEXT,
    event_detail TEXT,
    event_detail_2 TEXT,
    event_successful TEXT,
    shift_index DECIMAL,
    duration DECIMAL,
    time_start_total_seconds DECIMAL,
    time_end_total_seconds DECIMAL,
    running_intermission_duration DECIMAL,
    period_start_total_running_seconds DECIMAL,
    running_video_time DECIMAL,
    event_running_start DECIMAL,
    event_running_end DECIMAL,
    period_id TEXT,
    venue_id TEXT,
    event_type_id TEXT,
    event_detail_id TEXT,
    event_detail_2_id TEXT,
    success_id TEXT,
    play_detail_success_id TEXT,
    zone_id TEXT,
    play_detail_id TEXT,
    play_detail_2_id TEXT,
    home_team_id TEXT,
    away_team_id TEXT,
    shift_key TEXT,
    empty_net_goal INTEGER
);
CREATE INDEX idx_fact_events_game_id ON fact_events(game_id);

-- fact_events_player: 63 columns
CREATE TABLE fact_events_player (
    event_player_key TEXT PRIMARY KEY,
    event_key TEXT,
    game_id TEXT,
    player_id TEXT,
    event_index DECIMAL,
    player_role TEXT,
    role_number DECIMAL,
    period DECIMAL,
    event_type TEXT,
    player_game_number DECIMAL,
    linked_event_index DECIMAL,
    tracking_event_index DECIMAL,
    event_start_min DECIMAL,
    event_start_sec DECIMAL,
    event_end_min DECIMAL,
    event_end_sec DECIMAL,
    role_abrev TEXT,
    event_team_zone TEXT,
    home_team_zone TEXT,
    away_team_zone TEXT,
    team_venue TEXT,
    team_venue_abv TEXT,
    side_of_puck TEXT,
    sequence_index DECIMAL,
    play_index DECIMAL,
    play_detail1 TEXT,
    play_detail_2 TEXT,
    play_detail_successful TEXT,
    pressured_pressurer DECIMAL,
    zone_change_index DECIMAL,
    home_team TEXT,
    away_team TEXT,
    Type TEXT,
    event_detail TEXT,
    event_detail_2 TEXT,
    event_successful TEXT,
    shift_index DECIMAL,
    duration DECIMAL,
    time_start_total_seconds DECIMAL,
    time_end_total_seconds DECIMAL,
    running_intermission_duration DECIMAL,
    period_start_total_running_seconds DECIMAL,
    running_video_time DECIMAL,
    event_running_start DECIMAL,
    event_running_end DECIMAL,
    player_team TEXT,
    player_name TEXT,
    play_detail TEXT,
    period_id TEXT,
    venue_id TEXT,
    event_type_id TEXT,
    event_detail_id TEXT,
    event_detail_2_id TEXT,
    success_id TEXT,
    play_detail_success_id TEXT,
    zone_id TEXT,
    play_detail_id TEXT,
    play_detail_2_id TEXT,
    role_id TEXT,
    home_team_id TEXT,
    away_team_id TEXT,
    player_team_id TEXT,
    shift_key TEXT
);
CREATE INDEX idx_fact_events_player_game_id ON fact_events_player(game_id);
CREATE INDEX idx_fact_events_player_player_id ON fact_events_player(player_id);

-- fact_shifts_player: 35 columns
CREATE TABLE fact_shifts_player (
    shift_player_key TEXT PRIMARY KEY,
    shift_key TEXT,
    game_id TEXT,
    shift_index INTEGER,
    player_number INTEGER,
    venue TEXT,
    slot TEXT,
    period DECIMAL,
    shift_duration DECIMAL,
    situation TEXT,
    strength TEXT,
    stoppage_time DECIMAL,
    pm_plus_ev DECIMAL,
    pm_minus_ev DECIMAL,
    goal_for INTEGER,
    goal_against INTEGER,
    team_en DECIMAL,
    opp_en DECIMAL,
    team_pp DECIMAL,
    team_pk DECIMAL,
    player_id TEXT,
    player_name TEXT,
    logical_shift_number INTEGER,
    shift_segment INTEGER,
    cumulative_shift_duration DECIMAL,
    running_toi DECIMAL,
    playing_duration DECIMAL,
    running_playing_toi DECIMAL,
    period_id TEXT,
    venue_id TEXT,
    strength_id TEXT,
    situation_id TEXT,
    slot_id TEXT,
    team_id TEXT,
    team_name TEXT
);
CREATE INDEX idx_fact_shifts_player_game_id ON fact_shifts_player(game_id);
CREATE INDEX idx_fact_shifts_player_player_id ON fact_shifts_player(player_id);

-- fact_player_game_stats: 317 columns
CREATE TABLE fact_player_game_stats (
    player_game_key TEXT PRIMARY KEY,
    game_id TEXT,
    player_id TEXT,
    player_name TEXT,
    goals INTEGER,
    assists INTEGER,
    points INTEGER,
    shots INTEGER,
    sog INTEGER,
    shots_blocked INTEGER,
    shots_missed INTEGER,
    shooting_pct DECIMAL,
    pass_attempts INTEGER,
    pass_completed INTEGER,
    pass_pct DECIMAL,
    fo_wins INTEGER,
    fo_losses INTEGER,
    fo_total INTEGER,
    fo_pct DECIMAL,
    zone_entries INTEGER,
    zone_exits INTEGER,
    giveaways INTEGER,
    takeaways INTEGER,
    toi_seconds DECIMAL,
    toi_minutes DECIMAL,
    playing_toi_seconds DECIMAL,
    playing_toi_minutes DECIMAL,
    stoppage_seconds DECIMAL,
    shift_count INTEGER,
    logical_shifts INTEGER,
    avg_shift DECIMAL,
    avg_playing_shift DECIMAL,
    goals_per_60 DECIMAL,
    assists_per_60 DECIMAL,
    points_per_60 DECIMAL,
    shots_per_60 DECIMAL,
    goals_per_60_playing DECIMAL,
    assists_per_60_playing DECIMAL,
    points_per_60_playing DECIMAL,
    shots_per_60_playing DECIMAL,
    blocks INTEGER,
    hits INTEGER,
    puck_battles INTEGER,
    puck_battle_wins INTEGER,
    retrievals INTEGER,
    corsi_for INTEGER,
    corsi_against INTEGER,
    fenwick_for INTEGER,
    fenwick_against INTEGER,
    cf_pct DECIMAL,
    ff_pct DECIMAL,
    opp_avg_rating DECIMAL,
    skill_diff DECIMAL,
    plus_ev INTEGER,
    minus_ev INTEGER,
    plus_minus_ev INTEGER,
    plus_total INTEGER,
    minus_total INTEGER,
    plus_minus_total INTEGER,
    plus_en_adj INTEGER,
    minus_en_adj INTEGER,
    plus_minus_en_adj INTEGER,
    player_rating DECIMAL,
    home_team_id TEXT,
    away_team_id TEXT,
    chips INTEGER,
    breakout_rush_attempts INTEGER,
    zone_keepins INTEGER,
    dekes_successful INTEGER,
    breakout_clear_attempts INTEGER,
    beat_middle INTEGER,
    beat_wide INTEGER,
    zone_exit_denials INTEGER,
    breakouts INTEGER,
    passes_missed_target INTEGER,
    drives_corner INTEGER,
    tip_attempts INTEGER,
    cutbacks INTEGER,
    drives_middle INTEGER,
    pass_for_tip INTEGER,
    poke_checks INTEGER,
    stick_checks INTEGER,
    got_beat_middle INTEGER,
    crash_net INTEGER,
    cycle_plays INTEGER,
    ceded_exits INTEGER,
    reverse_passes INTEGER,
    deke_attempts INTEGER,
    breakout_pass_attempts INTEGER,
    backchecks INTEGER,
    separate_from_puck INTEGER,
    rebound_recoveries INTEGER,
    block_attempts INTEGER,
    drives_net INTEGER,
    ceded_entries INTEGER,
    puck_retrievals INTEGER,
    passes_intercepted INTEGER,
    stopped_deke INTEGER,
    dump_and_chase INTEGER,
    def_pass_deflected INTEGER,
    loose_puck_wins INTEGER,
    drives_wide INTEGER,
    puck_recoveries INTEGER,
    def_pass_intercepted INTEGER,
    screens INTEGER,
    front_of_net INTEGER,
    secondary_assists INTEGER,
    in_lane INTEGER,
    quick_ups INTEGER,
    second_touches INTEGER,
    delays INTEGER,
    loose_puck_losses INTEGER,
    turnover_recoveries INTEGER,
    dump_recoveries INTEGER,
    pressures INTEGER,
    contains INTEGER,
    forechecks INTEGER,
    give_and_go INTEGER,
    passes_deflected INTEGER,
    lost_puck INTEGER,
    force_wide INTEGER,
    man_on_man INTEGER,
    dekes_beat_defender INTEGER,
    box_outs INTEGER,
    primary_assists INTEGER,
    got_beat_wide INTEGER,
    zone_entry_denials INTEGER,
    surf_plays INTEGER,
    blocked_shots_play INTEGER,
    drives_middle_success INTEGER,
    drives_wide_success INTEGER,
    drives_corner_success INTEGER,
    zone_entry_denials_success INTEGER,
    breakouts_success INTEGER,
    zone_entry_carry DECIMAL,
    zone_entry_pass DECIMAL,
    zone_entry_dump DECIMAL,
    zone_exit_carry DECIMAL,
    zone_exit_pass DECIMAL,
    zone_exit_dump DECIMAL,
    zone_exit_clear DECIMAL,
    zone_entries_controlled DECIMAL,
    zone_entries_uncontrolled DECIMAL,
    zone_entry_success_rate DECIMAL,
    zone_entry_control_pct DECIMAL,
    zone_exits_controlled DECIMAL,
    zone_exits_uncontrolled DECIMAL,
    zone_exit_success_rate DECIMAL,
    zone_exit_control_pct DECIMAL,
    def_shots_against INTEGER,
    def_goals_against INTEGER,
    def_entries_allowed INTEGER,
    def_exits_denied INTEGER,
    def_times_beat_deke INTEGER,
    def_times_beat_speed INTEGER,
    def_times_beat_total INTEGER,
    def_takeaways INTEGER,
    def_forced_turnovers INTEGER,
    def_zone_clears INTEGER,
    def_blocked_shots INTEGER,
    def_interceptions INTEGER,
    def_stick_checks INTEGER,
    def_poke_checks INTEGER,
    def_body_checks INTEGER,
    def_coverage_assignments INTEGER,
    def_battles_won INTEGER,
    def_battles_lost INTEGER,
    giveaways_bad DECIMAL,
    giveaways_neutral DECIMAL,
    giveaways_good DECIMAL,
    turnover_diff_adjusted DECIMAL,
    turnovers_oz DECIMAL,
    turnovers_nz DECIMAL,
    turnovers_dz DECIMAL,
    giveaway_rate_per_60 DECIMAL,
    takeaway_rate_per_60 DECIMAL,
    goals_rating_adj DECIMAL,
    assists_rating_adj DECIMAL,
    points_rating_adj DECIMAL,
    plus_minus_rating_adj DECIMAL,
    cf_pct_rating_adj DECIMAL,
    qoc_rating DECIMAL,
    qot_rating DECIMAL,
    expected_vs_rating DECIMAL,
    xg_for DECIMAL,
    xg_against DECIMAL,
    xg_diff DECIMAL,
    xg_pct DECIMAL,
    goals_above_expected DECIMAL,
    shots_high_danger DECIMAL,
    shots_medium_danger DECIMAL,
    shots_low_danger DECIMAL,
    scoring_chances DECIMAL,
    high_danger_chances DECIMAL,
    xg_per_shot DECIMAL,
    shot_quality_avg DECIMAL,
    offensive_rating DECIMAL,
    defensive_rating DECIMAL,
    hustle_rating DECIMAL,
    playmaking_rating DECIMAL,
    shooting_rating DECIMAL,
    physical_rating DECIMAL,
    impact_score DECIMAL,
    war_estimate DECIMAL,
    avg_shift_too_long DECIMAL,
    shift_length_warning DECIMAL,
    fatigue_indicator DECIMAL,
    sub_equity_score DECIMAL,
    toi_vs_team_avg DECIMAL,
    period_3_dropoff DECIMAL,
    late_game_performance DECIMAL,
    on_ice_sh_pct DECIMAL,
    on_ice_sv_pct DECIMAL,
    pdo DECIMAL,
    pdo_5v5 DECIMAL,
    fo_wins_oz DECIMAL,
    fo_wins_nz DECIMAL,
    fo_wins_dz DECIMAL,
    fo_losses_oz DECIMAL,
    fo_losses_nz DECIMAL,
    fo_losses_dz DECIMAL,
    fo_pct_oz DECIMAL,
    fo_pct_nz DECIMAL,
    fo_pct_dz DECIMAL,
    zone_starts_oz_pct DECIMAL,
    zone_starts_dz_pct DECIMAL,
    game_score DECIMAL,
    game_score_per_60 DECIMAL,
    game_score_rating DECIMAL,
    effective_game_rating DECIMAL,
    rating_performance_delta DECIMAL,
    playing_above_rating INTEGER,
    playing_below_rating INTEGER,
    playing_at_rating INTEGER,
    performance_tier TEXT,
    performance_index DECIMAL,
    shots_successful DECIMAL,
    shots_unsuccessful DECIMAL,
    passes_successful DECIMAL,
    passes_unsuccessful DECIMAL,
    plays_successful DECIMAL,
    plays_unsuccessful DECIMAL,
    entries_successful DECIMAL,
    entries_unsuccessful DECIMAL,
    exits_successful DECIMAL,
    exits_unsuccessful DECIMAL,
    total_successful_plays DECIMAL,
    total_unsuccessful_plays DECIMAL,
    overall_success_rate DECIMAL,
    shot_success_rate DECIMAL,
    pass_success_rate DECIMAL,
    play_success_rate DECIMAL,
    times_pass_target DECIMAL,
    passes_received_successful DECIMAL,
    passes_received_unsuccessful DECIMAL,
    pass_reception_rate DECIMAL,
    times_target_oz DECIMAL,
    times_target_nz DECIMAL,
    times_target_dz DECIMAL,
    slot_passes_received DECIMAL,
    cross_ice_passes_received DECIMAL,
    odd_man_rushes INTEGER,
    odd_man_rush_goals INTEGER,
    odd_man_rush_shots INTEGER,
    breakaway_attempts INTEGER,
    breakaway_goals INTEGER,
    2on1_rushes INTEGER,
    3on2_rushes INTEGER,
    2on0_rushes INTEGER,
    rush_entries INTEGER,
    rush_shots INTEGER,
    rush_goals INTEGER,
    counter_attacks INTEGER,
    transition_plays INTEGER,
    times_targeted_by_opp DECIMAL,
    times_targeted_shots DECIMAL,
    times_targeted_entries DECIMAL,
    times_targeted_passes DECIMAL,
    times_targeted_as_defender DECIMAL,
    defensive_assignments DECIMAL,
    times_attacked DECIMAL,
    times_attacked_successfully DECIMAL,
    times_attacked_unsuccessfully DECIMAL,
    defensive_success_rate DECIMAL,
    times_ep3 DECIMAL,
    times_ep4 DECIMAL,
    times_ep5 DECIMAL,
    times_opp2 DECIMAL,
    times_opp3 DECIMAL,
    times_opp4 DECIMAL,
    total_on_ice_events DECIMAL,
    puck_touches_estimated DECIMAL,
    involvement_rate DECIMAL,
    support_plays DECIMAL,
    goals_leading INTEGER,
    goals_trailing INTEGER,
    goals_tied INTEGER,
    shots_leading INTEGER,
    shots_trailing INTEGER,
    shots_tied INTEGER,
    first_period_points INTEGER,
    second_period_points INTEGER,
    third_period_points INTEGER,
    first_period_shots INTEGER,
    second_period_shots INTEGER,
    third_period_shots INTEGER,
    clutch_goals INTEGER,
    empty_net_goals_for INTEGER,
    shorthanded_goals INTEGER,
    offensive_contribution DECIMAL,
    defensive_contribution DECIMAL,
    two_way_rating DECIMAL,
    puck_possession_index DECIMAL,
    danger_creation_rate DECIMAL,
    efficiency_score DECIMAL,
    clutch_factor DECIMAL,
    complete_player_score DECIMAL
);
CREATE INDEX idx_fact_player_game_stats_game_id ON fact_player_game_stats(game_id);
CREATE INDEX idx_fact_player_game_stats_player_id ON fact_player_game_stats(player_id);

-- fact_team_game_stats: 52 columns
CREATE TABLE fact_team_game_stats (
    team_game_key TEXT PRIMARY KEY,
    game_id TEXT,
    venue TEXT,
    goals INTEGER,
    shots INTEGER,
    fo_wins INTEGER,
    giveaways INTEGER,
    takeaways INTEGER,
    zone_entries INTEGER,
    zone_exits INTEGER,
    pass_attempts INTEGER,
    pass_completed INTEGER,
    fo_losses INTEGER,
    sog INTEGER,
    fo_total INTEGER,
    fo_pct DECIMAL,
    pass_pct DECIMAL,
    shooting_pct DECIMAL,
    venue_id TEXT,
    home_team_id TEXT,
    away_team_id TEXT,
    team_id TEXT,
    total_shots DECIMAL,
    total_sog DECIMAL,
    total_passes DECIMAL,
    total_pass_completed DECIMAL,
    team_pass_pct DECIMAL,
    total_zone_entries DECIMAL,
    total_zone_exits DECIMAL,
    controlled_entries DECIMAL,
    controlled_exits DECIMAL,
    entry_control_pct DECIMAL,
    total_giveaways DECIMAL,
    total_takeaways DECIMAL,
    turnover_diff DECIMAL,
    total_blocks DECIMAL,
    total_hits DECIMAL,
    total_fo_wins DECIMAL,
    total_fo_losses DECIMAL,
    corsi_for DECIMAL,
    corsi_against DECIMAL,
    cf_pct DECIMAL,
    xg_for DECIMAL,
    xg_against DECIMAL,
    xg_diff DECIMAL,
    avg_player_rating DECIMAL,
    total_dekes DECIMAL,
    total_screens DECIMAL,
    offensive_rating_avg DECIMAL,
    defensive_rating_avg DECIMAL,
    hustle_rating_avg DECIMAL,
    team_name TEXT
);
CREATE INDEX idx_fact_team_game_stats_game_id ON fact_team_game_stats(game_id);

-- fact_goalie_game_stats: 19 columns
CREATE TABLE fact_goalie_game_stats (
    goalie_game_key TEXT PRIMARY KEY,
    game_id TEXT,
    player_id TEXT,
    player_name TEXT,
    team_name TEXT,
    saves INTEGER,
    goals_against INTEGER,
    shots_against INTEGER,
    save_pct DECIMAL,
    toi_seconds INTEGER,
    empty_net_ga INTEGER,
    saves_rebound DECIMAL,
    saves_freeze DECIMAL,
    saves_glove DECIMAL,
    saves_blocker DECIMAL,
    saves_left_pad DECIMAL,
    saves_right_pad DECIMAL,
    rebound_control_pct DECIMAL,
    total_save_events DECIMAL
);
CREATE INDEX idx_fact_goalie_game_stats_game_id ON fact_goalie_game_stats(game_id);
CREATE INDEX idx_fact_goalie_game_stats_player_id ON fact_goalie_game_stats(player_id);

-- fact_h2h: 24 columns
CREATE TABLE fact_h2h (
    game_id TEXT,
    player_1_id TEXT,
    player_2_id TEXT,
    shifts_together INTEGER,
    home_team_id TEXT,
    away_team_id TEXT,
    toi_together DECIMAL,
    goals_for DECIMAL,
    goals_against DECIMAL,
    plus_minus DECIMAL,
    corsi_for DECIMAL,
    corsi_against DECIMAL,
    cf_pct DECIMAL,
    fenwick_for DECIMAL,
    fenwick_against DECIMAL,
    ff_pct DECIMAL,
    xgf DECIMAL,
    xga DECIMAL,
    xg_diff DECIMAL,
    shots_for DECIMAL,
    shots_against DECIMAL,
    h2h_key TEXT PRIMARY KEY,
    player_1_name TEXT,
    player_2_name TEXT
);
CREATE INDEX idx_fact_h2h_game_id ON fact_h2h(game_id);

-- fact_wowy: 28 columns
CREATE TABLE fact_wowy (
    game_id TEXT,
    player_1_id TEXT,
    player_2_id TEXT,
    venue TEXT,
    shifts_together INTEGER,
    p1_shifts_without_p2 INTEGER,
    p2_shifts_without_p1 INTEGER,
    p1_logical_shifts INTEGER,
    p2_logical_shifts INTEGER,
    venue_id TEXT,
    home_team_id TEXT,
    away_team_id TEXT,
    toi_together DECIMAL,
    toi_apart DECIMAL,
    gf_pct_together DECIMAL,
    gf_pct_apart DECIMAL,
    gf_pct_delta DECIMAL,
    cf_pct_together DECIMAL,
    cf_pct_apart DECIMAL,
    cf_pct_delta DECIMAL,
    xgf_pct_together DECIMAL,
    xgf_pct_apart DECIMAL,
    xgf_pct_delta DECIMAL,
    relative_corsi DECIMAL,
    relative_fenwick DECIMAL,
    wowy_key TEXT PRIMARY KEY,
    player_1_name TEXT,
    player_2_name TEXT
);
CREATE INDEX idx_fact_wowy_game_id ON fact_wowy(game_id);

-- ============================================================
-- HELPER FUNCTIONS
-- ============================================================

-- Function to truncate all fact tables (for reloading)
CREATE OR REPLACE FUNCTION truncate_all_facts()
RETURNS void AS $$
BEGIN
    TRUNCATE TABLE fact_wowy CASCADE;
    TRUNCATE TABLE fact_h2h CASCADE;
    TRUNCATE TABLE fact_goalie_game_stats CASCADE;
    TRUNCATE TABLE fact_team_game_stats CASCADE;
    TRUNCATE TABLE fact_player_game_stats CASCADE;
    TRUNCATE TABLE fact_shifts_player CASCADE;
    TRUNCATE TABLE fact_events_player CASCADE;
    TRUNCATE TABLE fact_events CASCADE;
    TRUNCATE TABLE fact_shifts CASCADE;
END;
$$ LANGUAGE plpgsql;

-- Function to get row counts
CREATE OR REPLACE FUNCTION get_table_counts()
RETURNS TABLE(table_name TEXT, row_count BIGINT) AS $$
BEGIN
    RETURN QUERY
    SELECT 'dim_player'::TEXT, COUNT(*)::BIGINT FROM dim_player UNION ALL
    SELECT 'dim_team'::TEXT, COUNT(*)::BIGINT FROM dim_team UNION ALL
    SELECT 'dim_schedule'::TEXT, COUNT(*)::BIGINT FROM dim_schedule UNION ALL
    SELECT 'fact_shifts'::TEXT, COUNT(*)::BIGINT FROM fact_shifts UNION ALL
    SELECT 'fact_events'::TEXT, COUNT(*)::BIGINT FROM fact_events UNION ALL
    SELECT 'fact_events_player'::TEXT, COUNT(*)::BIGINT FROM fact_events_player UNION ALL
    SELECT 'fact_shifts_player'::TEXT, COUNT(*)::BIGINT FROM fact_shifts_player UNION ALL
    SELECT 'fact_player_game_stats'::TEXT, COUNT(*)::BIGINT FROM fact_player_game_stats UNION ALL
    SELECT 'fact_team_game_stats'::TEXT, COUNT(*)::BIGINT FROM fact_team_game_stats UNION ALL
    SELECT 'fact_goalie_game_stats'::TEXT, COUNT(*)::BIGINT FROM fact_goalie_game_stats UNION ALL
    SELECT 'fact_h2h'::TEXT, COUNT(*)::BIGINT FROM fact_h2h UNION ALL
    SELECT 'fact_wowy'::TEXT, COUNT(*)::BIGINT FROM fact_wowy;
END;
$$ LANGUAGE plpgsql;