
CREATE TABLE public."fact_suspicious_stats" (
    "game_id" BIGINT,
    "player_id" TEXT,
    "player_name" TEXT,
    "position" TEXT,
    "stat_name" TEXT,
    "stat_value" DOUBLE PRECISION,
    "threshold" BIGINT,
    "threshold_direction" TEXT,
    "flag_type" TEXT,
    "severity" TEXT,
    "category" TEXT,
    "note" TEXT,
    "resolved" BOOLEAN,
    "created_at" TEXT
);


CREATE TABLE public."fact_team_game_stats" (
    "team_game_key" TEXT,
    "game_id" BIGINT,
    "team_id" TEXT,
    "team_name" TEXT,
    "shots" BIGINT,
    "sog" BIGINT,
    "goals" BIGINT,
    "giveaways" BIGINT,
    "takeaways" BIGINT,
    "blocks" BIGINT,
    "hits" BIGINT,
    "assists" DOUBLE PRECISION,
    "points" DOUBLE PRECISION,
    "toi_seconds" BIGINT,
    "corsi_for" BIGINT,
    "corsi_against" BIGINT,
    "fenwick_for" BIGINT,
    "fenwick_against" BIGINT,
    "plus_total" BIGINT,
    "minus_total" BIGINT,
    "xg_for" DOUBLE PRECISION,
    "gar_total" DOUBLE PRECISION,
    "war" DOUBLE PRECISION,
    "shot_assists" BIGINT,
    "goal_creating_actions" BIGINT,
    "dekes" BIGINT,
    "drives_total" BIGINT,
    "cutbacks" BIGINT,
    "delays" BIGINT,
    "crash_net" BIGINT,
    "screens" BIGINT,
    "give_and_go" BIGINT,
    "second_touch" BIGINT,
    "cycles" BIGINT,
    "poke_checks" BIGINT,
    "stick_checks" BIGINT,
    "zone_ent_denials" BIGINT,
    "backchecks" BIGINT,
    "forechecks" BIGINT,
    "breakouts" BIGINT,
    "dump_ins" BIGINT,
    "loose_puck_wins" BIGINT,
    "puck_recoveries" BIGINT,
    "puck_battles_total" BIGINT,
    "board_battles_won" BIGINT,
    "board_battles_lost" BIGINT,
    "passes_cross_ice" BIGINT,
    "passes_stretch" BIGINT,
    "passes_breakout" BIGINT,
    "passes_rim" BIGINT,
    "passes_bank" BIGINT,
    "passes_royal_road" BIGINT,
    "passes_slot" BIGINT,
    "passes_behind_net" BIGINT,
    "shots_one_timer" BIGINT,
    "shots_snap" BIGINT,
    "shots_wrist" BIGINT,
    "shots_slap" BIGINT,
    "shots_tip" BIGINT,
    "shots_deflection" BIGINT,
    "shots_wrap_around" BIGINT,
    "pressure_plays" BIGINT,
    "pressure_successful" BIGINT,
    "possession_quality_index" DOUBLE PRECISION,
    "transition_efficiency" DOUBLE PRECISION,
    "pressure_index" DOUBLE PRECISION,
    "offensive_creativity_index" DOUBLE PRECISION,
    "defensive_activity_index" DOUBLE PRECISION,
    "playmaking_quality" DOUBLE PRECISION,
    "net_front_presence" DOUBLE PRECISION,
    "puck_battles_per_60" DOUBLE PRECISION,
    "shooting_pct" DOUBLE PRECISION,
    "cf_pct" DOUBLE PRECISION,
    "plus_minus_total" BIGINT,
    "avg_game_score" DOUBLE PRECISION,
    "avg_adjusted_rating" DOUBLE PRECISION
);


CREATE TABLE public."fact_team_season_stats" (
    "team_season_key" TEXT,
    "team_id" TEXT,
    "games_played" BIGINT,
    "season_goals" BIGINT,
    "season_shots" BIGINT,
    "season_sog" BIGINT,
    "avg_goals_per_game" DOUBLE PRECISION,
    "avg_shots_per_game" DOUBLE PRECISION,
    "avg_sog_per_game" DOUBLE PRECISION
);


CREATE TABLE public."fact_team_season_stats_basic" (
    "team_season_basic_key" TEXT,
    "team_id" TEXT,
    "team_name" TEXT,
    "season_id" TEXT,
    "season" BIGINT,
    "game_type" TEXT,
    "games_played" BIGINT,
    "wins" BIGINT,
    "losses" BIGINT,
    "ties" BIGINT,
    "win_pct" DOUBLE PRECISION,
    "points" BIGINT,
    "goals_for" BIGINT,
    "goals_against" BIGINT,
    "goal_diff" BIGINT,
    "goals_for_per_game" DOUBLE PRECISION,
    "goals_against_per_game" DOUBLE PRECISION,
    "team_goals" DOUBLE PRECISION,
    "team_assists" DOUBLE PRECISION,
    "team_pim" DOUBLE PRECISION,
    "unique_players" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_team_zone_time" (
    "zone_time_key" TEXT,
    "game_id" BIGINT,
    "venue" TEXT,
    "offensive_zone_events" BIGINT,
    "neutral_zone_events" BIGINT,
    "defensive_zone_events" BIGINT,
    "oz_pct" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


-- Error with fact_time_period_momentum: No columns to parse from file

CREATE TABLE public."fact_tracking" (
    "tracking_event_key" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "running_video_time" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "event_team_zone" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "x_coord" DOUBLE PRECISION,
    "y_coord" DOUBLE PRECISION,
    "time_bucket_id" TEXT,
    "strength_id" TEXT
);


CREATE TABLE public."fact_turnovers_detailed" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" DOUBLE PRECISION,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" DOUBLE PRECISION,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "giveaway_type_id" TEXT,
    "takeaway_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" DOUBLE PRECISION,
    "danger_level_id" DOUBLE PRECISION,
    "scoring_chance_key" DOUBLE PRECISION,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "turnover_key_new" TEXT
);


CREATE TABLE public."fact_video" (
    "video_key" TEXT,
    "game_id" BIGINT,
    "video_type_id" TEXT,
    "video_type" TEXT,
    "video_description" TEXT,
    "video_url" TEXT,
    "period_1_start" BIGINT,
    "period_2_start" BIGINT,
    "period_3_start" BIGINT,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_wowy" (
    "wowy_key" TEXT,
    "game_id" BIGINT,
    "player_1_id" TEXT,
    "player_2_id" TEXT,
    "venue" TEXT,
    "shifts_together" BIGINT,
    "p1_total_shifts" BIGINT,
    "p2_total_shifts" BIGINT,
    "p1_shifts_without_p2" BIGINT,
    "p2_shifts_without_p1" BIGINT,
    "toi_together" DOUBLE PRECISION,
    "toi_apart" DOUBLE PRECISION,
    "toi_p1_without_p2" DOUBLE PRECISION,
    "toi_p2_without_p1" DOUBLE PRECISION,
    "cf_together" BIGINT,
    "ca_together" BIGINT,
    "cf_pct_together" DOUBLE PRECISION,
    "gf_together" BIGINT,
    "ga_together" BIGINT,
    "gf_pct_together" DOUBLE PRECISION,
    "cf_apart" BIGINT,
    "ca_apart" BIGINT,
    "cf_pct_apart" DOUBLE PRECISION,
    "gf_apart" BIGINT,
    "ga_apart" BIGINT,
    "gf_pct_apart" DOUBLE PRECISION,
    "cf_pct_delta" DOUBLE PRECISION,
    "gf_pct_delta" DOUBLE PRECISION,
    "relative_corsi" DOUBLE PRECISION,
    "player_1_name" TEXT,
    "player_2_name" TEXT,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "venue_id" TEXT
);


CREATE TABLE public."fact_zone_entries" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "zone_entry_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "zone_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" DOUBLE PRECISION,
    "danger_level_id" DOUBLE PRECISION,
    "scoring_chance_key" DOUBLE PRECISION,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "time_from_entry_to_shot" DOUBLE PRECISION,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "zone_entry_key" TEXT,
    "entry_method" TEXT,
    "entry_successful" TEXT,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "event_player_4_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "opp_player_3_toi" DOUBLE PRECISION,
    "opp_player_4_toi" DOUBLE PRECISION,
    "opp_player_5_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION
);


CREATE TABLE public."fact_zone_entry_summary" (
    "zone_entry_key" TEXT,
    "game_id" BIGINT,
    "player_id" TEXT,
    "total_entries" BIGINT,
    "controlled_entries" BIGINT,
    "dump_entries" BIGINT,
    "failed_entries" BIGINT,
    "entry_success_rate" DOUBLE PRECISION,
    "_export_timestamp" TEXT,
    "player_name" TEXT
);


CREATE TABLE public."fact_zone_exit_summary" (
    "zone_exit_key" TEXT,
    "player_id" TEXT,
    "games" BIGINT,
    "total_exits" BIGINT,
    "exits_per_game" DOUBLE PRECISION
);


CREATE TABLE public."fact_zone_exits" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "zone_entry_type_id" DOUBLE PRECISION,
    "zone_exit_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "zone_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" DOUBLE PRECISION,
    "danger_level_id" DOUBLE PRECISION,
    "scoring_chance_key" DOUBLE PRECISION,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "zone_exit_key" TEXT,
    "exit_method" TEXT,
    "exit_successful" TEXT,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "event_player_4_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION
);


CREATE TABLE public."lookup_player_game_rating" (
    "game_id" BIGINT,
    "player_id" TEXT,
    "avg_rating" DOUBLE PRECISION,
    "avg_opp_rating" DOUBLE PRECISION,
    "lookup_key" TEXT,
    "_export_timestamp" TEXT,
    "player_name" TEXT
);


CREATE TABLE public."qa_data_completeness" (
    "qa_key" TEXT,
    "game_id" BIGINT,
    "has_events" BOOLEAN,
    "has_shifts" BOOLEAN,
    "has_rosters" BOOLEAN,
    "is_complete" BOOLEAN,
    "check_date" TEXT
);


CREATE TABLE public."qa_goal_accuracy" (
    "qa_key" TEXT,
    "game_id" BIGINT,
    "game_date" TEXT,
    "home_team" TEXT,
    "away_team" TEXT,
    "expected_goals" BIGINT,
    "actual_goals" BIGINT,
    "match" BOOLEAN,
    "difference" BIGINT,
    "check_date" TEXT
);


CREATE TABLE public."qa_scorer_comparison" (
    "comparison_key" TEXT,
    "game_id" BIGINT,
    "metric" TEXT,
    "events_value" BIGINT,
    "stats_value" DOUBLE PRECISION,
    "match" BOOLEAN,
    "difference" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."qa_suspicious_stats" (
    "suspicious_key" TEXT,
    "game_id" BIGINT,
    "player_id" TEXT,
    "flags" TEXT,
    "goals" DOUBLE PRECISION,
    "shots" DOUBLE PRECISION,
    "toi_minutes" DOUBLE PRECISION,
    "_export_timestamp" TEXT,
    "player_name" TEXT
);