
CREATE TABLE public."fact_draft" (
    "team_id" TEXT,
    "skill_rating" BIGINT,
    "round" BIGINT,
    "player_full_name" TEXT,
    "player_id" TEXT,
    "team_name" TEXT,
    "restricted" BOOLEAN,
    "overall_draft_round" BIGINT,
    "overall_draft_position" BIGINT,
    "unrestricted_draft_position" BIGINT,
    "season" BIGINT,
    "season_id" TEXT,
    "league" TEXT,
    "player_draft_id" TEXT
);


CREATE TABLE public."fact_event_chains" (
    "chain_key" TEXT,
    "game_id" BIGINT,
    "event_count" BIGINT,
    "event_1_type" TEXT,
    "event_1_detail" TEXT,
    "event_1_player_id" TEXT,
    "event_2_type" TEXT,
    "event_2_detail" TEXT,
    "event_2_player_id" TEXT,
    "play_chain" TEXT,
    "event_3_type" TEXT,
    "event_3_detail" TEXT,
    "event_3_player_id" TEXT,
    "event_4_type" TEXT,
    "event_4_detail" TEXT,
    "event_4_player_id" TEXT,
    "event_5_type" TEXT,
    "event_5_player_id" TEXT
);


CREATE TABLE public."fact_event_players" (
    "event_player_key" TEXT,
    "game_id" BIGINT,
    "event_id" TEXT,
    "event_index" BIGINT,
    "player_id" TEXT,
    "player_role" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "tracking_event_key" TEXT,
    "zone_change_key" TEXT,
    "period_id" TEXT,
    "event_type_id" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2_id" TEXT,
    "event_success_id" TEXT,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "player_team_id" TEXT,
    "player_role_id" TEXT,
    "play_detail_id" TEXT,
    "play_detail_2_id" TEXT,
    "play_success_id" TEXT,
    "event_type" TEXT,
    "period" BIGINT,
    "assist_to_goal_index" DOUBLE PRECISION,
    "assist_primary_event_index" DOUBLE PRECISION,
    "assist_secondary_event_index" DOUBLE PRECISION,
    "home_team" TEXT,
    "away_team" TEXT,
    "strength" TEXT,
    "event_team_zone" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "event_type_code" TEXT,
    "event_detail_code" TEXT,
    "event_detail_2_code" TEXT,
    "event_detail" TEXT,
    "event_detail_2" TEXT,
    "event_successful" TEXT,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "duration" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_video_time" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_intermission_duration" BIGINT,
    "is_highlight" BIGINT,
    "video_url" DOUBLE PRECISION,
    "pim" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "puck_x_start_adjusted" DOUBLE PRECISION,
    "puck_y_start_adjusted" DOUBLE PRECISION,
    "puck_x_stop" DOUBLE PRECISION,
    "puck_y_stop" DOUBLE PRECISION,
    "puck_x_stop_adjusted" DOUBLE PRECISION,
    "puck_y_stop_adjusted" DOUBLE PRECISION,
    "is_xy_adjusted" DOUBLE PRECISION,
    "needs_xy_adjustment" DOUBLE PRECISION,
    "role_abrev_binary" TEXT,
    "player_name" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "side_of_puck" TEXT,
    "player_x_start" DOUBLE PRECISION,
    "player_y_start" DOUBLE PRECISION,
    "player_x_start_adjusted" DOUBLE PRECISION,
    "player_y_start_adjusted" DOUBLE PRECISION,
    "player_x_stop" DOUBLE PRECISION,
    "player_y_stop" DOUBLE PRECISION,
    "player_x_stop_adjusted" DOUBLE PRECISION,
    "player_y_stop_adjusted" DOUBLE PRECISION,
    "net_x" DOUBLE PRECISION,
    "net_y" DOUBLE PRECISION,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "play_detail1_s" TEXT,
    "play_detail2_s" TEXT,
    "is_goal" BIGINT,
    "shift_id" TEXT,
    "position_id" DOUBLE PRECISION,
    "stoppage_type_id" TEXT,
    "giveaway_type_id" TEXT,
    "takeaway_type_id" TEXT,
    "time_bucket_id" TEXT,
    "strength_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "player_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION,
    "event_team_avg_rating" DOUBLE PRECISION,
    "opp_team_avg_rating" DOUBLE PRECISION,
    "rating_vs_opp" DOUBLE PRECISION,
    "success_id" TEXT,
    "game_state_id" TEXT,
    "competition_tier_id" TEXT,
    "turnover_quality_id" TEXT
);


CREATE TABLE public."fact_events" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "shot_type_id" TEXT,
    "zone_entry_type_id" TEXT,
    "zone_exit_type_id" TEXT,
    "stoppage_type_id" TEXT,
    "giveaway_type_id" TEXT,
    "takeaway_type_id" TEXT,
    "pass_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" TEXT,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "shooter_player_id" TEXT,
    "shooter_name" TEXT,
    "shooter_rating" DOUBLE PRECISION,
    "shot_blocker_player_id" DOUBLE PRECISION,
    "shot_blocker_name" DOUBLE PRECISION,
    "shot_blocker_rating" DOUBLE PRECISION,
    "goalie_player_id" TEXT,
    "goalie_name" TEXT,
    "goalie_rating" DOUBLE PRECISION,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "shot_outcome_id" TEXT,
    "pass_outcome_id" TEXT,
    "save_outcome_id" TEXT,
    "zone_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" TEXT,
    "danger_level_id" TEXT,
    "scoring_chance_key" TEXT,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "time_from_entry_to_shot" DOUBLE PRECISION,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "opp_player_3_toi" DOUBLE PRECISION,
    "event_player_4_toi" DOUBLE PRECISION,
    "opp_player_4_toi" DOUBLE PRECISION,
    "opp_player_5_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION,
    "event_team_avg_rating" DOUBLE PRECISION,
    "opp_team_avg_rating" DOUBLE PRECISION,
    "rating_vs_opp" DOUBLE PRECISION,
    "game_state_id" TEXT,
    "competition_tier_id" TEXT,
    "turnover_quality_id" TEXT
);


CREATE TABLE public."fact_faceoffs" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" DOUBLE PRECISION,
    "danger_level_id" DOUBLE PRECISION,
    "scoring_chance_key" DOUBLE PRECISION,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "faceoff_key" TEXT,
    "faceoff_type" TEXT,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION
);


CREATE TABLE public."fact_game_status" (
    "game_id" BIGINT,
    "game_date" TEXT,
    "home_team" TEXT,
    "away_team" TEXT,
    "official_home_goals" BIGINT,
    "official_away_goals" BIGINT,
    "official_total_goals" BIGINT,
    "game_url" TEXT,
    "tracking_status" TEXT,
    "tracking_pct" DOUBLE PRECISION,
    "events_row_count" BIGINT,
    "shifts_row_count" BIGINT,
    "player_id_fill_pct" DOUBLE PRECISION,
    "goal_events" BIGINT,
    "periods_covered" DOUBLE PRECISION,
    "is_loaded" BOOLEAN,
    "goals_in_stats" BIGINT,
    "goal_match" DOUBLE PRECISION,
    "player_count" BIGINT,
    "issues" TEXT,
    "suspicious_stats_flag" BOOLEAN,
    "suspicious_stats_count" BIGINT,
    "suspicious_stats_summary" DOUBLE PRECISION
);


CREATE TABLE public."fact_gameroster" (
    "game_id" BIGINT,
    "player_id" TEXT,
    "team_id" TEXT,
    "opp_team_id" TEXT,
    "season_id" TEXT,
    "venue_id" TEXT,
    "position_id" TEXT,
    "team_name" TEXT,
    "opp_team_name" TEXT,
    "team_venue" TEXT,
    "date" TEXT,
    "season" BIGINT,
    "player_full_name" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "player_position" TEXT,
    "goals" DOUBLE PRECISION,
    "assist" DOUBLE PRECISION,
    "points" DOUBLE PRECISION,
    "goals_against" DOUBLE PRECISION,
    "pim" DOUBLE PRECISION,
    "shutouts" DOUBLE PRECISION,
    "games_played" DOUBLE PRECISION,
    "sub" DOUBLE PRECISION,
    "current_team" TEXT
);


CREATE TABLE public."fact_goal_assists" (
    "goal_assist_key" TEXT,
    "game_id" BIGINT,
    "goal_event_id" TEXT,
    "goal_event_index" BIGINT,
    "period" BIGINT,
    "time_minutes" BIGINT,
    "time_seconds" BIGINT,
    "time_total_seconds" BIGINT,
    "scorer_player_id" TEXT,
    "scorer_player_name" TEXT,
    "scorer_team_id" TEXT,
    "scorer_team_name" TEXT,
    "primary_assist_player_id" TEXT,
    "primary_assist_player_name" TEXT,
    "primary_assist_event_id" TEXT,
    "secondary_assist_player_id" TEXT,
    "secondary_assist_player_name" TEXT,
    "secondary_assist_event_id" TEXT,
    "strength" TEXT,
    "shot_type" TEXT,
    "assist_count" BIGINT,
    "is_unassisted" BOOLEAN,
    "is_powerplay_goal" BOOLEAN,
    "is_shorthanded_goal" BOOLEAN,
    "is_empty_net" BOOLEAN,
    "is_game_winner" BOOLEAN,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "home_team_name" TEXT,
    "away_team_name" TEXT,
    "video_url" TEXT,
    "running_video_time" BIGINT,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_goalie_career_stats" (
    "goalie_career_key" TEXT,
    "player_id" TEXT,
    "season_id" TEXT,
    "game_type" TEXT,
    "player_name" TEXT,
    "team_name" TEXT,
    "team_id" TEXT,
    "career_games" BIGINT,
    "career_save_pct" DOUBLE PRECISION,
    "career_gaa" DOUBLE PRECISION,
    "_export_timestamp" TEXT,
    "career_saves" DOUBLE PRECISION,
    "career_goals_against" DOUBLE PRECISION,
    "career_shots_against" DOUBLE PRECISION,
    "career_saves_butterfly" DOUBLE PRECISION,
    "career_saves_pad" DOUBLE PRECISION,
    "career_saves_glove" DOUBLE PRECISION,
    "career_saves_blocker" DOUBLE PRECISION,
    "career_saves_chest" DOUBLE PRECISION,
    "career_saves_stick" DOUBLE PRECISION,
    "career_saves_scramble" DOUBLE PRECISION,
    "career_hd_shots_against" DOUBLE PRECISION,
    "career_hd_goals_against" DOUBLE PRECISION,
    "career_hd_saves" DOUBLE PRECISION,
    "career_saves_freeze" DOUBLE PRECISION,
    "career_saves_rebound" DOUBLE PRECISION,
    "career_rebounds_team_recovered" DOUBLE PRECISION,
    "career_rebounds_opp_recovered" DOUBLE PRECISION,
    "career_rebounds_shot_generated" DOUBLE PRECISION,
    "career_rebounds_flurry_generated" DOUBLE PRECISION,
    "career_p1_saves" DOUBLE PRECISION,
    "career_p1_goals_against" DOUBLE PRECISION,
    "career_p2_saves" DOUBLE PRECISION,
    "career_p2_goals_against" DOUBLE PRECISION,
    "career_p3_saves" DOUBLE PRECISION,
    "career_p3_goals_against" DOUBLE PRECISION,
    "career_early_period_saves" DOUBLE PRECISION,
    "career_mid_period_saves" DOUBLE PRECISION,
    "career_late_period_saves" DOUBLE PRECISION,
    "career_final_minute_saves" DOUBLE PRECISION,
    "career_early_period_ga" DOUBLE PRECISION,
    "career_mid_period_ga" DOUBLE PRECISION,
    "career_late_period_ga" DOUBLE PRECISION,
    "career_final_minute_ga" DOUBLE PRECISION,
    "career_rush_saves" DOUBLE PRECISION,
    "career_quick_attack_saves" DOUBLE PRECISION,
    "career_set_play_saves" DOUBLE PRECISION,
    "career_rush_goals_against" DOUBLE PRECISION,
    "career_quick_attack_ga" DOUBLE PRECISION,
    "career_set_play_ga" DOUBLE PRECISION,
    "career_single_shot_saves" DOUBLE PRECISION,
    "career_multi_shot_saves" DOUBLE PRECISION,
    "career_sustained_pressure_saves" DOUBLE PRECISION,
    "career_glove_side_saves" DOUBLE PRECISION,
    "career_blocker_side_saves" DOUBLE PRECISION,
    "career_five_hole_saves" DOUBLE PRECISION,
    "career_rapid_fire_saves" DOUBLE PRECISION,
    "career_is_quality_start" DOUBLE PRECISION,
    "career_is_bad_start" DOUBLE PRECISION,
    "career_goalie_war" DOUBLE PRECISION,
    "career_goalie_game_score" DOUBLE PRECISION,
    "career_overall_game_rating" DOUBLE PRECISION,
    "career_clutch_rating" DOUBLE PRECISION,
    "career_pressure_rating" DOUBLE PRECISION,
    "career_rebound_rating" DOUBLE PRECISION
);


CREATE TABLE public."fact_goalie_career_stats_basic" (
    "goalie_career_basic_key" TEXT,
    "player_id" TEXT,
    "season_id" TEXT,
    "game_type" TEXT,
    "player_name" TEXT,
    "current_team" TEXT,
    "career_games" BIGINT,
    "career_wins" BIGINT,
    "career_losses" BIGINT,
    "career_ties" BIGINT,
    "career_goals_against" BIGINT,
    "career_gaa" DOUBLE PRECISION,
    "career_shutouts" BIGINT,
    "career_shutout_pct" DOUBLE PRECISION,
    "career_win_pct" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_goalie_game_stats" (
    "goalie_game_key" TEXT,
    "game_id" BIGINT,
    "player_id" TEXT,
    "_export_timestamp" TEXT,
    "player_name" TEXT,
    "team_name" TEXT,
    "team_id" TEXT,
    "is_home" BOOLEAN,
    "saves" BIGINT,
    "goals_against" BIGINT,
    "shots_against" BIGINT,
    "save_pct" DOUBLE PRECISION,
    "saves_butterfly" BIGINT,
    "saves_pad" BIGINT,
    "saves_glove" BIGINT,
    "saves_blocker" BIGINT,
    "saves_chest" BIGINT,
    "saves_stick" BIGINT,
    "saves_scramble" BIGINT,
    "hd_shots_against" BIGINT,
    "hd_goals_against" BIGINT,
    "hd_saves" BIGINT,
    "hd_save_pct" DOUBLE PRECISION,
    "saves_freeze" BIGINT,
    "saves_rebound" BIGINT,
    "freeze_pct" DOUBLE PRECISION,
    "rebound_rate" DOUBLE PRECISION,
    "rebounds_team_recovered" BIGINT,
    "rebounds_opp_recovered" BIGINT,
    "rebounds_shot_generated" BIGINT,
    "rebounds_flurry_generated" BIGINT,
    "rebound_control_rate" DOUBLE PRECISION,
    "rebound_danger_rate" DOUBLE PRECISION,
    "second_chance_shots_against" BIGINT,
    "second_chance_goals_against" BIGINT,
    "second_chance_sv_pct" DOUBLE PRECISION,
    "dangerous_rebound_pct" DOUBLE PRECISION,
    "p1_saves" BIGINT,
    "p1_goals_against" BIGINT,
    "p1_shots_against" BIGINT,
    "p1_sv_pct" DOUBLE PRECISION,
    "p2_saves" BIGINT,
    "p2_goals_against" BIGINT,
    "p2_shots_against" BIGINT,
    "p2_sv_pct" DOUBLE PRECISION,
    "p3_saves" BIGINT,
    "p3_goals_against" BIGINT,
    "p3_shots_against" BIGINT,
    "p3_sv_pct" DOUBLE PRECISION,
    "best_period" BIGINT,
    "worst_period" BIGINT,
    "period_consistency" DOUBLE PRECISION,
    "early_period_saves" BIGINT,
    "mid_period_saves" BIGINT,
    "late_period_saves" BIGINT,
    "final_minute_saves" BIGINT,
    "early_period_ga" BIGINT,
    "mid_period_ga" BIGINT,
    "late_period_ga" BIGINT,
    "final_minute_ga" BIGINT,
    "early_period_sv_pct" DOUBLE PRECISION,
    "mid_period_sv_pct" DOUBLE PRECISION,
    "late_period_sv_pct" DOUBLE PRECISION,
    "final_minute_sv_pct" DOUBLE PRECISION,
    "rush_saves" BIGINT,
    "quick_attack_saves" BIGINT,
    "set_play_saves" BIGINT,
    "avg_time_from_entry" DOUBLE PRECISION,
    "rush_goals_against" BIGINT,
    "quick_attack_ga" BIGINT,
    "set_play_ga" BIGINT,
    "rush_sv_pct" DOUBLE PRECISION,
    "quick_attack_sv_pct" DOUBLE PRECISION,
    "set_play_sv_pct" DOUBLE PRECISION,
    "rush_pct_of_shots" DOUBLE PRECISION,
    "transition_defense_rating" DOUBLE PRECISION,
    "single_shot_saves" BIGINT,
    "multi_shot_saves" BIGINT,
    "sustained_pressure_saves" BIGINT,
    "max_sequence_faced" BIGINT,
    "avg_sequence_length" DOUBLE PRECISION,
    "multi_shot_sv_pct" DOUBLE PRECISION,
    "sustained_pressure_sv_pct" DOUBLE PRECISION,
    "sequence_survival_rate" DOUBLE PRECISION,
    "pressure_handling_index" DOUBLE PRECISION,
    "glove_side_saves" BIGINT,
    "blocker_side_saves" BIGINT,
    "five_hole_saves" BIGINT,
    "glove_side_ga" BIGINT,
    "blocker_side_ga" BIGINT,
    "five_hole_ga" BIGINT,
    "glove_side_sv_pct" DOUBLE PRECISION,
    "blocker_side_sv_pct" DOUBLE PRECISION,
    "five_hole_sv_pct" DOUBLE PRECISION,
    "side_preference_ratio" DOUBLE PRECISION,
    "shots_per_period" DOUBLE PRECISION,
    "saves_per_period" DOUBLE PRECISION,
    "max_shots_in_period" BIGINT,
    "shot_volume_variance" DOUBLE PRECISION,
    "time_between_shots_avg" DOUBLE PRECISION,
    "time_between_shots_min" DOUBLE PRECISION,
    "rapid_fire_saves" BIGINT,
    "consecutive_saves_max" BIGINT,
    "workload_index" DOUBLE PRECISION,
    "fatigue_adjusted_gsaa" DOUBLE PRECISION,
    "is_quality_start" BIGINT,
    "is_bad_start" BIGINT,
    "expected_goals_against" DOUBLE PRECISION,
    "goals_saved_above_avg" DOUBLE PRECISION,
    "goalie_game_score" DOUBLE PRECISION,
    "goalie_gax" DOUBLE PRECISION,
    "goalie_gsax" DOUBLE PRECISION,
    "clutch_rating" DOUBLE PRECISION,
    "consistency_rating" DOUBLE PRECISION,
    "pressure_rating" DOUBLE PRECISION,
    "rebound_rating" DOUBLE PRECISION,
    "positioning_rating" DOUBLE PRECISION,
    "overall_game_rating" DOUBLE PRECISION,
    "win_probability_added" DOUBLE PRECISION,
    "goalie_gar_gsaa" DOUBLE PRECISION,
    "goalie_gar_hd_bonus" DOUBLE PRECISION,
    "goalie_gar_qs_bonus" DOUBLE PRECISION,
    "goalie_gar_rebound" DOUBLE PRECISION,
    "goalie_gar_total" DOUBLE PRECISION,
    "goalie_war" DOUBLE PRECISION,
    "goalie_war_pace" DOUBLE PRECISION,
    "venue" TEXT,
    "venue_id" TEXT
);


CREATE TABLE public."fact_goalie_season_stats" (
    "goalie_season_key" TEXT,
    "player_id" TEXT,
    "season_id" TEXT,
    "season" BIGINT,
    "game_type" TEXT,
    "player_name" TEXT,
    "team_name" TEXT,
    "team_id" TEXT,
    "games_played" BIGINT,
    "saves" BIGINT,
    "goals_against" BIGINT,
    "shots_against" BIGINT,
    "saves_butterfly" BIGINT,
    "saves_pad" BIGINT,
    "saves_glove" BIGINT,
    "saves_blocker" BIGINT,
    "saves_chest" BIGINT,
    "saves_stick" BIGINT,
    "saves_scramble" BIGINT,
    "hd_shots_against" BIGINT,
    "hd_goals_against" BIGINT,
    "hd_saves" BIGINT,
    "saves_freeze" BIGINT,
    "saves_rebound" BIGINT,
    "rebounds_team_recovered" BIGINT,
    "rebounds_opp_recovered" BIGINT,
    "rebounds_shot_generated" BIGINT,
    "rebounds_flurry_generated" BIGINT,
    "p1_saves" BIGINT,
    "p1_goals_against" BIGINT,
    "p2_saves" BIGINT,
    "p2_goals_against" BIGINT,
    "p3_saves" BIGINT,
    "p3_goals_against" BIGINT,
    "early_period_saves" BIGINT,
    "mid_period_saves" BIGINT,
    "late_period_saves" BIGINT,
    "final_minute_saves" BIGINT,
    "early_period_ga" BIGINT,
    "mid_period_ga" BIGINT,
    "late_period_ga" BIGINT,
    "final_minute_ga" BIGINT,
    "rush_saves" BIGINT,
    "quick_attack_saves" BIGINT,
    "set_play_saves" BIGINT,
    "rush_goals_against" BIGINT,
    "quick_attack_ga" BIGINT,
    "set_play_ga" BIGINT,
    "single_shot_saves" BIGINT,
    "multi_shot_saves" BIGINT,
    "sustained_pressure_saves" BIGINT,
    "glove_side_saves" BIGINT,
    "blocker_side_saves" BIGINT,
    "five_hole_saves" BIGINT,
    "rapid_fire_saves" BIGINT,
    "is_quality_start" BIGINT,
    "is_bad_start" BIGINT,
    "goalie_war" DOUBLE PRECISION,
    "goalie_game_score" DOUBLE PRECISION,
    "overall_game_rating" DOUBLE PRECISION,
    "clutch_rating" DOUBLE PRECISION,
    "pressure_rating" DOUBLE PRECISION,
    "rebound_rating" DOUBLE PRECISION,
    "save_pct" DOUBLE PRECISION,
    "gaa" DOUBLE PRECISION,
    "hd_save_pct" DOUBLE PRECISION,
    "saves_per_game" DOUBLE PRECISION,
    "shots_against_per_game" DOUBLE PRECISION,
    "rebound_control_rate" DOUBLE PRECISION,
    "rush_sv_pct" DOUBLE PRECISION,
    "set_play_sv_pct" DOUBLE PRECISION,
    "quality_start_pct" DOUBLE PRECISION,
    "season_war" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_goalie_season_stats_basic" (
    "goalie_season_basic_key" TEXT,
    "player_id" TEXT,
    "season_id" TEXT,
    "season" BIGINT,
    "game_type" TEXT,
    "player_name" TEXT,
    "team_id" TEXT,
    "team_name" TEXT,
    "games_played" BIGINT,
    "wins" BIGINT,
    "losses" BIGINT,
    "ties" BIGINT,
    "goals_against" BIGINT,
    "gaa" DOUBLE PRECISION,
    "shutouts" BIGINT,
    "shutout_pct" DOUBLE PRECISION,
    "win_pct" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_goals" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" TEXT,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "shot_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "shooter_player_id" TEXT,
    "shooter_name" TEXT,
    "shooter_rating" DOUBLE PRECISION,
    "goalie_player_id" TEXT,
    "goalie_name" TEXT,
    "goalie_rating" DOUBLE PRECISION,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "shot_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" TEXT,
    "danger_level_id" TEXT,
    "scoring_chance_key" TEXT,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION,
    "event_team_avg_rating" DOUBLE PRECISION,
    "opp_team_avg_rating" DOUBLE PRECISION,
    "rating_vs_opp" DOUBLE PRECISION,
    "goal_key" TEXT,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_h2h" (
    "h2h_key" TEXT,
    "game_id" BIGINT,
    "player_1_id" TEXT,
    "player_1_name" TEXT,
    "player_2_id" TEXT,
    "player_2_name" TEXT,
    "same_team" BOOLEAN,
    "venue" TEXT,
    "shifts_together" BIGINT,
    "toi_together" DOUBLE PRECISION,
    "goals_for" BIGINT,
    "goals_against" BIGINT,
    "plus_minus" BIGINT,
    "corsi_for" BIGINT,
    "corsi_against" BIGINT,
    "cf_pct" DOUBLE PRECISION,
    "fenwick_for" BIGINT,
    "fenwick_against" BIGINT,
    "ff_pct" DOUBLE PRECISION,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "venue_id" TEXT
);


CREATE TABLE public."fact_high_danger_chances" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" TEXT,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "shot_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" TEXT,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "shooter_player_id" TEXT,
    "shooter_name" TEXT,
    "shooter_rating" DOUBLE PRECISION,
    "goalie_player_id" TEXT,
    "goalie_name" TEXT,
    "goalie_rating" DOUBLE PRECISION,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "shot_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" TEXT,
    "danger_level_id" TEXT,
    "scoring_chance_key" TEXT,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "high_danger_key" TEXT
);


CREATE TABLE public."fact_highlights" (
    "highlight_key" TEXT,
    "event_id" TEXT,
    "game_id" BIGINT,
    "video_key" TEXT,
    "highlight_category_id" TEXT,
    "period" BIGINT,
    "event_type" TEXT,
    "event_detail" TEXT,
    "video_start_time" BIGINT,
    "video_end_time" BIGINT,
    "duration_seconds" BIGINT,
    "event_time_display" TEXT,
    "description" TEXT,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_leadership" (
    "player_full_name" TEXT,
    "player_id" TEXT,
    "leadership" TEXT,
    "skill_rating" BIGINT,
    "n_player_url" TEXT,
    "team_name" TEXT,
    "team_id" TEXT,
    "season" BIGINT,
    "season_id" TEXT
);


CREATE TABLE public."fact_line_combos" (
    "line_combo_key" TEXT,
    "game_id" BIGINT,
    "venue" TEXT,
    "combo_type" TEXT,
    "forward_combo" TEXT,
    "forward_combo_ids" TEXT,
    "forward_jersey_numbers" TEXT,
    "shifts" BIGINT,
    "toi_together" DOUBLE PRECISION,
    "goals_for" BIGINT,
    "goals_against" BIGINT,
    "plus_minus" BIGINT,
    "corsi_for" BIGINT,
    "corsi_against" BIGINT,
    "cf_pct" DOUBLE PRECISION,
    "fenwick_for" BIGINT,
    "fenwick_against" BIGINT,
    "ff_pct" DOUBLE PRECISION,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "venue_id" TEXT
);


CREATE TABLE public."fact_linked_events" (
    "linked_event_key" TEXT,
    "game_id" BIGINT,
    "event_count" BIGINT,
    "event_1_type" TEXT,
    "event_1_detail" TEXT,
    "event_1_player_id" TEXT,
    "event_2_type" TEXT,
    "event_2_detail" TEXT,
    "event_2_player_id" TEXT,
    "play_chain" TEXT,
    "event_3_type" TEXT,
    "event_3_detail" TEXT,
    "event_3_player_id" TEXT,
    "event_4_type" TEXT,
    "event_4_detail" TEXT,
    "event_4_player_id" TEXT,
    "event_5_type" TEXT,
    "event_5_player_id" TEXT
);