

CREATE TABLE public."fact_penalties" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" DOUBLE PRECISION,
    "linked_event_key" TEXT,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" DOUBLE PRECISION,
    "event_player_2_name_y" DOUBLE PRECISION,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" DOUBLE PRECISION,
    "danger_level_id" DOUBLE PRECISION,
    "scoring_chance_key" DOUBLE PRECISION,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "penalty_key" TEXT
);



CREATE TABLE public."fact_period_momentum" (
    "momentum_key" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "events_count" BIGINT,
    "goals" BIGINT,
    "shots" BIGINT,
    "passes" BIGINT
);



CREATE TABLE public."fact_player_boxscore_all" (
    "player_game_key" TEXT,
    "player_game_id" TEXT,
    "game_id" BIGINT,
    "player_id" TEXT,
    "player_name" TEXT,
    "team_id" TEXT,
    "team_name" TEXT,
    "position" TEXT,
    "_export_timestamp" TEXT,
    "goals" DOUBLE PRECISION,
    "primary_assists" DOUBLE PRECISION,
    "secondary_assists" DOUBLE PRECISION,
    "assists" DOUBLE PRECISION,
    "points" DOUBLE PRECISION,
    "shots" DOUBLE PRECISION,
    "sog" DOUBLE PRECISION,
    "shooting_pct" DOUBLE PRECISION,
    "pass_attempts" DOUBLE PRECISION,
    "pass_completed" DOUBLE PRECISION,
    "pass_pct" DOUBLE PRECISION,
    "fo_wins" DOUBLE PRECISION,
    "fo_losses" DOUBLE PRECISION,
    "fo_total" DOUBLE PRECISION,
    "fo_pct" DOUBLE PRECISION,
    "giveaways" DOUBLE PRECISION,
    "takeaways" DOUBLE PRECISION,
    "turnover_diff" DOUBLE PRECISION,
    "bad_giveaways" DOUBLE PRECISION,
    "bad_turnover_diff" DOUBLE PRECISION,
    "blocks" DOUBLE PRECISION,
    "hits" DOUBLE PRECISION,
    "primary_def_events" DOUBLE PRECISION,
    "support_def_events" DOUBLE PRECISION,
    "def_involvement" DOUBLE PRECISION,
    "primary_def_shots" DOUBLE PRECISION,
    "primary_def_goals_against" DOUBLE PRECISION,
    "primary_def_passes" DOUBLE PRECISION,
    "toi_seconds" BIGINT,
    "toi_minutes" DOUBLE PRECISION,
    "shift_count" BIGINT,
    "avg_shift" DOUBLE PRECISION,
    "plus_ev" BIGINT,
    "minus_ev" BIGINT,
    "plus_minus_ev" BIGINT,
    "corsi_for" BIGINT,
    "corsi_against" BIGINT,
    "cf_pct" DOUBLE PRECISION,
    "player_rating" DOUBLE PRECISION,
    "team_avg_rating" DOUBLE PRECISION,
    "opp_avg_rating" DOUBLE PRECISION,
    "team_rating_diff" DOUBLE PRECISION,
    "rating_diff" DOUBLE PRECISION,
    "team_min_rating_avg" DOUBLE PRECISION,
    "team_max_rating_avg" DOUBLE PRECISION,
    "opp_min_rating_avg" DOUBLE PRECISION,
    "opp_max_rating_avg" DOUBLE PRECISION,
    "min_rating_diff" DOUBLE PRECISION,
    "max_rating_diff" DOUBLE PRECISION,
    "fenwick_for" BIGINT,
    "fenwick_against" BIGINT,
    "ff_pct" DOUBLE PRECISION,
    "on_ice_sh_pct" DOUBLE PRECISION,
    "on_ice_sv_pct" DOUBLE PRECISION,
    "pdo" DOUBLE PRECISION,
    "qoc_rating" DOUBLE PRECISION,
    "qot_rating" DOUBLE PRECISION,
    "zone_starts_oz" BIGINT,
    "zone_starts_nz" BIGINT,
    "zone_starts_dz" BIGINT,
    "zone_starts_oz_pct" DOUBLE PRECISION,
    "zone_starts_dz_pct" DOUBLE PRECISION,
    "plus_total" BIGINT,
    "minus_total" BIGINT,
    "plus_minus_total" BIGINT,
    "scoring_chances_for" BIGINT,
    "scoring_chances_against" BIGINT,
    "sc_pct" DOUBLE PRECISION,
    "high_danger_for" BIGINT,
    "high_danger_against" BIGINT,
    "hd_pct" DOUBLE PRECISION,
    "zone_ent_total" BIGINT,
    "zone_ent_controlled" BIGINT,
    "zone_ent_uncontrolled" BIGINT,
    "zone_ent_control_pct" DOUBLE PRECISION,
    "zone_ent_successful" BIGINT,
    "zone_ent_success_pct" DOUBLE PRECISION,
    "zone_ent_controlled_successful" BIGINT,
    "zone_ent_controlled_success_pct" DOUBLE PRECISION,
    "zone_ent_uncontrolled_successful" BIGINT,
    "zone_ent_uncontrolled_success_pct" DOUBLE PRECISION,
    "zone_ent_shot_generated" DOUBLE PRECISION,
    "zone_ent_shot_generated_pct" DOUBLE PRECISION,
    "zone_ent_goal_generated" DOUBLE PRECISION,
    "zone_ent_goal_generated_pct" DOUBLE PRECISION,
    "zone_ent_controlled_shot" DOUBLE PRECISION,
    "zone_ent_controlled_shot_pct" DOUBLE PRECISION,
    "zone_ent_controlled_goal" DOUBLE PRECISION,
    "zone_ent_controlled_goal_pct" DOUBLE PRECISION,
    "zone_ent_uncontrolled_shot" DOUBLE PRECISION,
    "zone_ent_uncontrolled_shot_pct" DOUBLE PRECISION,
    "zone_ent_uncontrolled_goal" DOUBLE PRECISION,
    "zone_ent_uncontrolled_goal_pct" DOUBLE PRECISION,
    "zone_ext_total" BIGINT,
    "zone_ext_controlled" BIGINT,
    "zone_ext_uncontrolled" BIGINT,
    "zone_ext_control_pct" DOUBLE PRECISION,
    "zone_ext_successful" BIGINT,
    "zone_ext_success_pct" DOUBLE PRECISION,
    "zone_ext_controlled_successful" BIGINT,
    "zone_ext_controlled_success_pct" DOUBLE PRECISION,
    "zone_ext_uncontrolled_successful" BIGINT,
    "zone_ext_uncontrolled_success_pct" DOUBLE PRECISION,
    "zone_ext_shot_generated" DOUBLE PRECISION,
    "zone_ext_shot_generated_pct" DOUBLE PRECISION,
    "zone_ext_goal_generated" DOUBLE PRECISION,
    "zone_ext_goal_generated_pct" DOUBLE PRECISION,
    "zone_ext_controlled_shot" DOUBLE PRECISION,
    "zone_ext_controlled_shot_pct" DOUBLE PRECISION,
    "zone_ext_controlled_goal" DOUBLE PRECISION,
    "zone_ext_controlled_goal_pct" DOUBLE PRECISION,
    "zone_ext_uncontrolled_shot" DOUBLE PRECISION,
    "zone_ext_uncontrolled_shot_pct" DOUBLE PRECISION,
    "zone_ext_uncontrolled_goal" DOUBLE PRECISION,
    "zone_ext_uncontrolled_goal_pct" DOUBLE PRECISION,
    "possession_time_offensive_zone" BIGINT,
    "possession_time_defensive_zone" BIGINT,
    "possession_time_neutral_zone" BIGINT,
    "possession_time_o" BIGINT,
    "possession_time_d" BIGINT,
    "possession_time_n" BIGINT,
    "possession_time_total" BIGINT,
    "possession_events_count" BIGINT,
    "fo_wins_oz" BIGINT,
    "fo_wins_nz" BIGINT,
    "fo_wins_dz" BIGINT,
    "fo_losses_oz" BIGINT,
    "fo_losses_nz" BIGINT,
    "fo_losses_dz" BIGINT,
    "fo_pct_oz" DOUBLE PRECISION,
    "fo_pct_nz" DOUBLE PRECISION,
    "fo_pct_dz" DOUBLE PRECISION,
    "faceoffs_clean_wins" BIGINT,
    "faceoffs_scrum_wins" BIGINT,
    "faceoffs_wdbe_value" DOUBLE PRECISION,
    "faceoff_wdbe_rate" DOUBLE PRECISION,
    "p1_goals" BIGINT,
    "p1_assists" BIGINT,
    "p1_shots" BIGINT,
    "p1_sog" BIGINT,
    "p1_points" BIGINT,
    "p1_toi_seconds" BIGINT,
    "p2_goals" BIGINT,
    "p2_assists" BIGINT,
    "p2_shots" BIGINT,
    "p2_sog" BIGINT,
    "p2_points" BIGINT,
    "p2_toi_seconds" BIGINT,
    "p3_goals" BIGINT,
    "p3_assists" BIGINT,
    "p3_shots" BIGINT,
    "p3_sog" BIGINT,
    "p3_points" BIGINT,
    "p3_toi_seconds" BIGINT,
    "p3_clutch_diff" DOUBLE PRECISION,
    "shots_high_danger" BIGINT,
    "goals_high_danger" BIGINT,
    "shots_low_danger" BIGINT,
    "goals_low_danger" BIGINT,
    "shots_medium_danger" BIGINT,
    "goals_medium_danger" BIGINT,
    "scoring_chance_shots" BIGINT,
    "scoring_chance_goals" BIGINT,
    "scoring_chance_pct" DOUBLE PRECISION,
    "avg_shot_danger" DOUBLE PRECISION,
    "high_danger_shot_pct" DOUBLE PRECISION,
    "low_danger_shot_pct" DOUBLE PRECISION,
    "rush_shots" BIGINT,
    "rush_goals" BIGINT,
    "rush_assists" BIGINT,
    "rush_points" BIGINT,
    "rush_shot_pct" DOUBLE PRECISION,
    "breakaway_goals" BIGINT,
    "odd_man_rushes" BIGINT,
    "rush_xg" DOUBLE PRECISION,
    "rush_primary" BIGINT,
    "rush_support" BIGINT,
    "rush_involvement" BIGINT,
    "rush_involvement_pct" DOUBLE PRECISION,
    "rush_primary_def" BIGINT,
    "rush_def_support" BIGINT,
    "rush_def_involvement" BIGINT,
    "rush_def_involvement_pct" DOUBLE PRECISION,
    "rush_off_success" DOUBLE PRECISION,
    "rush_off_success_pct" DOUBLE PRECISION,
    "rush_off_shot_generated" DOUBLE PRECISION,
    "rush_off_shot_generated_pct" DOUBLE PRECISION,
    "rush_off_goal_generated" DOUBLE PRECISION,
    "rush_off_goal_generated_pct" DOUBLE PRECISION,
    "rush_off_immediate_shot" DOUBLE PRECISION,
    "rush_primary_success" BIGINT,
    "rush_primary_success_pct" DOUBLE PRECISION,
    "rush_primary_shot" BIGINT,
    "rush_primary_shot_pct" DOUBLE PRECISION,
    "rush_primary_goal" BIGINT,
    "rush_primary_goal_pct" DOUBLE PRECISION,
    "rush_support_success" BIGINT,
    "rush_support_success_pct" DOUBLE PRECISION,
    "rush_support_shot" BIGINT,
    "rush_support_shot_pct" DOUBLE PRECISION,
    "rush_support_goal" BIGINT,
    "rush_support_goal_pct" DOUBLE PRECISION,
    "rush_primary_def_success" BIGINT,
    "rush_primary_def_success_pct" DOUBLE PRECISION,
    "rush_primary_def_stop" BIGINT,
    "rush_primary_def_stop_pct" DOUBLE PRECISION,
    "rush_primary_def_ga" BIGINT,
    "rush_support_def_success" BIGINT,
    "rush_support_def_success_pct" DOUBLE PRECISION,
    "rush_support_def_stop" BIGINT,
    "rush_support_def_stop_pct" DOUBLE PRECISION,
    "rush_support_def_ga" BIGINT,
    "rush_calc_off" BIGINT,
    "rush_calc_def" BIGINT,
    "rush_calc_off_goal" BIGINT,
    "rush_calc_def_ga" BIGINT,
    "dekes" BIGINT,
    "dekes_successful" BIGINT,
    "dekes_unsuccessful" BIGINT,
    "dekes_success_rate" DOUBLE PRECISION,
    "drives_middle" BIGINT,
    "drives_middle_successful" BIGINT,
    "drives_middle_unsuccessful" BIGINT,
    "drives_middle_success_rate" DOUBLE PRECISION,
    "drives_wide" BIGINT,
    "drives_wide_successful" BIGINT,
    "drives_wide_unsuccessful" BIGINT,
    "drives_wide_success_rate" DOUBLE PRECISION,
    "drives_corner" BIGINT,
    "drives_corner_successful" BIGINT,
    "drives_corner_unsuccessful" BIGINT,
    "drives_corner_success_rate" DOUBLE PRECISION,
    "drives_net" BIGINT,
    "drives_net_successful" BIGINT,
    "drives_net_unsuccessful" BIGINT,
    "drives_net_success_rate" DOUBLE PRECISION,
    "cutbacks" BIGINT,
    "cutbacks_successful" BIGINT,
    "cutbacks_unsuccessful" BIGINT,
    "cutbacks_success_rate" DOUBLE PRECISION,
    "delays" BIGINT,
    "delays_successful" BIGINT,
    "delays_unsuccessful" BIGINT,
    "delays_success_rate" DOUBLE PRECISION,
    "fakes" BIGINT,
    "fakes_successful" BIGINT,
    "fakes_unsuccessful" BIGINT,
    "fakes_success_rate" DOUBLE PRECISION,
    "open_ice_dekes" BIGINT,
    "open_ice_dekes_successful" BIGINT,
    "open_ice_dekes_unsuccessful" BIGINT,
    "open_ice_dekes_success_rate" DOUBLE PRECISION,
    "crash_net" BIGINT,
    "crash_net_successful" BIGINT,
    "crash_net_unsuccessful" BIGINT,
    "crash_net_success_rate" DOUBLE PRECISION,
    "screens" BIGINT,
    "screens_successful" BIGINT,
    "screens_unsuccessful" BIGINT,
    "screens_success_rate" DOUBLE PRECISION,
    "net_front" BIGINT,
    "net_front_successful" BIGINT,
    "net_front_unsuccessful" BIGINT,
    "net_front_success_rate" DOUBLE PRECISION,
    "box_out" BIGINT,
    "box_out_successful" BIGINT,
    "box_out_unsuccessful" BIGINT,
    "box_out_success_rate" DOUBLE PRECISION,
    "give_and_go" BIGINT,
    "give_and_go_successful" BIGINT,
    "give_and_go_unsuccessful" BIGINT,
    "give_and_go_success_rate" DOUBLE PRECISION,
    "second_touch" BIGINT,
    "second_touch_successful" BIGINT,
    "second_touch_unsuccessful" BIGINT,
    "second_touch_success_rate" DOUBLE PRECISION,
    "cycles" BIGINT,
    "cycles_successful" BIGINT,
    "cycles_unsuccessful" BIGINT,
    "cycles_success_rate" DOUBLE PRECISION,
    "regroup" BIGINT,
    "regroup_successful" BIGINT,
    "regroup_unsuccessful" BIGINT,
    "regroup_success_rate" DOUBLE PRECISION,
    "reverse" BIGINT,
    "reverse_successful" BIGINT,
    "reverse_unsuccessful" BIGINT,
    "reverse_success_rate" DOUBLE PRECISION,
    "wheel" BIGINT,
    "wheel_successful" BIGINT,
    "wheel_unsuccessful" BIGINT,
    "wheel_success_rate" DOUBLE PRECISION,
    "surf" BIGINT,
    "surf_successful" BIGINT,
    "surf_unsuccessful" BIGINT,
    "surf_success_rate" DOUBLE PRECISION,
    "quick_up" BIGINT,
    "quick_up_successful" BIGINT,
    "quick_up_unsuccessful" BIGINT,
    "quick_up_success_rate" DOUBLE PRECISION,
    "chip" BIGINT,
    "chip_successful" BIGINT,
    "chip_unsuccessful" BIGINT,
    "chip_success_rate" DOUBLE PRECISION,
    "passes_cross_ice" BIGINT,
    "passes_cross_ice_successful" BIGINT,
    "passes_cross_ice_unsuccessful" BIGINT,
    "passes_cross_ice_success_rate" DOUBLE PRECISION,
    "passes_stretch" BIGINT,
    "passes_stretch_successful" BIGINT,
    "passes_stretch_unsuccessful" BIGINT,
    "passes_stretch_success_rate" DOUBLE PRECISION,
    "passes_breakout" BIGINT,
    "passes_breakout_successful" BIGINT,
    "passes_breakout_unsuccessful" BIGINT,
    "passes_breakout_success_rate" DOUBLE PRECISION,
    "passes_rim" BIGINT,
    "passes_rim_successful" BIGINT,
    "passes_rim_unsuccessful" BIGINT,
    "passes_rim_success_rate" DOUBLE PRECISION,
    "passes_bank" BIGINT,
    "passes_bank_successful" BIGINT,
    "passes_bank_unsuccessful" BIGINT,
    "passes_bank_success_rate" DOUBLE PRECISION,
    "passes_royal_road" BIGINT,
    "passes_royal_road_successful" BIGINT,
    "passes_royal_road_unsuccessful" BIGINT,
    "passes_royal_road_success_rate" DOUBLE PRECISION,
    "passes_slot" BIGINT,
    "passes_slot_successful" BIGINT,
    "passes_slot_unsuccessful" BIGINT,
    "passes_slot_success_rate" DOUBLE PRECISION,
    "passes_behind_net" BIGINT,
    "passes_behind_net_successful" BIGINT,
    "passes_behind_net_unsuccessful" BIGINT,
    "passes_behind_net_success_rate" DOUBLE PRECISION,
    "passes_for_tip" BIGINT,
    "passes_for_tip_successful" BIGINT,
    "passes_for_tip_unsuccessful" BIGINT,
    "passes_for_tip_success_rate" DOUBLE PRECISION,
    "passes_deflected" BIGINT,
    "passes_deflected_successful" BIGINT,
    "passes_deflected_unsuccessful" BIGINT,
    "passes_deflected_success_rate" DOUBLE PRECISION,
    "passes_intercepted" BIGINT,
    "passes_intercepted_successful" BIGINT,
    "passes_intercepted_unsuccessful" BIGINT,
    "passes_intercepted_success_rate" DOUBLE PRECISION,
    "passes_missed" BIGINT,
    "passes_missed_successful" BIGINT,
    "passes_missed_unsuccessful" BIGINT,
    "passes_missed_success_rate" DOUBLE PRECISION,
    "shots_one_timer" BIGINT,
    "shots_one_timer_successful" BIGINT,
    "shots_one_timer_unsuccessful" BIGINT,
    "shots_one_timer_success_rate" DOUBLE PRECISION,
    "shots_snap" BIGINT,
    "shots_snap_successful" BIGINT,
    "shots_snap_unsuccessful" BIGINT,
    "shots_snap_success_rate" DOUBLE PRECISION,
    "shots_wrist" BIGINT,
    "shots_wrist_successful" BIGINT,
    "shots_wrist_unsuccessful" BIGINT,
    "shots_wrist_success_rate" DOUBLE PRECISION,
    "shots_slap" BIGINT,
    "shots_slap_successful" BIGINT,
    "shots_slap_unsuccessful" BIGINT,
    "shots_slap_success_rate" DOUBLE PRECISION,
    "shots_tip" BIGINT,
    "shots_tip_successful" BIGINT,
    "shots_tip_unsuccessful" BIGINT,
    "shots_tip_success_rate" DOUBLE PRECISION,
    "shots_deflection" BIGINT,
    "shots_deflection_successful" BIGINT,
    "shots_deflection_unsuccessful" BIGINT,
    "shots_deflection_success_rate" DOUBLE PRECISION,
    "shots_wrap_around" BIGINT,
    "shots_wrap_around_successful" BIGINT,
    "shots_wrap_around_unsuccessful" BIGINT,
    "shots_wrap_around_success_rate" DOUBLE PRECISION,
    "shots_point" BIGINT,
    "shots_point_successful" BIGINT,
    "shots_point_unsuccessful" BIGINT,
    "shots_point_success_rate" DOUBLE PRECISION,
    "shots_attempted" BIGINT,
    "shots_attempted_successful" BIGINT,
    "shots_attempted_unsuccessful" BIGINT,
    "shots_attempted_success_rate" DOUBLE PRECISION,
    "rushes" BIGINT,
    "rushes_successful" BIGINT,
    "rushes_unsuccessful" BIGINT,
    "rushes_success_rate" DOUBLE PRECISION,
    "breakaways" BIGINT,
    "breakaways_successful" BIGINT,
    "breakaways_unsuccessful" BIGINT,
    "breakaways_success_rate" DOUBLE PRECISION,
    "odd_man_rushes_successful" BIGINT,
    "odd_man_rushes_unsuccessful" BIGINT,
    "odd_man_rushes_success_rate" DOUBLE PRECISION,
    "controlled_entries" BIGINT,
    "controlled_entries_successful" BIGINT,
    "controlled_entries_unsuccessful" BIGINT,
    "controlled_entries_success_rate" DOUBLE PRECISION,
    "dump_ins" BIGINT,
    "dump_ins_successful" BIGINT,
    "dump_ins_unsuccessful" BIGINT,
    "dump_ins_success_rate" DOUBLE PRECISION,
    "failed_entries" BIGINT,
    "failed_entries_successful" BIGINT,
    "failed_entries_unsuccessful" BIGINT,
    "failed_entries_success_rate" DOUBLE PRECISION,
    "keep_ins" BIGINT,
    "keep_ins_successful" BIGINT,
    "keep_ins_unsuccessful" BIGINT,
    "keep_ins_success_rate" DOUBLE PRECISION,
    "failed_keep_ins" BIGINT,
    "failed_keep_ins_successful" BIGINT,
    "failed_keep_ins_unsuccessful" BIGINT,
    "failed_keep_ins_success_rate" DOUBLE PRECISION,
    "poke_checks" BIGINT,
    "poke_checks_successful" BIGINT,
    "poke_checks_unsuccessful" BIGINT,
    "poke_checks_success_rate" DOUBLE PRECISION,
    "stick_checks" BIGINT,
    "stick_checks_successful" BIGINT,
    "stick_checks_unsuccessful" BIGINT,
    "stick_checks_success_rate" DOUBLE PRECISION,
    "zone_ent_denials" BIGINT,
    "zone_ent_denials_successful" BIGINT,
    "zone_ent_denials_unsuccessful" BIGINT,
    "zone_ent_denials_success_rate" DOUBLE PRECISION,
    "zone_exit_denials" BIGINT,
    "zone_exit_denials_successful" BIGINT,
    "zone_exit_denials_unsuccessful" BIGINT,
    "zone_exit_denials_success_rate" DOUBLE PRECISION,
    "backchecks" BIGINT,
    "backchecks_successful" BIGINT,
    "backchecks_unsuccessful" BIGINT,
    "backchecks_success_rate" DOUBLE PRECISION,
    "forechecks" BIGINT,
    "forechecks_successful" BIGINT,
    "forechecks_unsuccessful" BIGINT,
    "forechecks_success_rate" DOUBLE PRECISION,
    "contain" BIGINT,
    "contain_successful" BIGINT,
    "contain_unsuccessful" BIGINT,
    "contain_success_rate" DOUBLE PRECISION,
    "gap_control" BIGINT,
    "gap_control_successful" BIGINT,
    "gap_control_unsuccessful" BIGINT,
    "gap_control_success_rate" DOUBLE PRECISION,
    "man_on_man" BIGINT,
    "man_on_man_successful" BIGINT,
    "man_on_man_unsuccessful" BIGINT,
    "man_on_man_success_rate" DOUBLE PRECISION,
    "force_wide" BIGINT,
    "force_wide_successful" BIGINT,
    "force_wide_unsuccessful" BIGINT,
    "force_wide_success_rate" DOUBLE PRECISION,
    "forced_dumpins" BIGINT,
    "forced_dumpins_successful" BIGINT,
    "forced_dumpins_unsuccessful" BIGINT,
    "forced_dumpins_success_rate" DOUBLE PRECISION,
    "forced_turnovers" BIGINT,
    "forced_turnovers_successful" BIGINT,
    "forced_turnovers_unsuccessful" BIGINT,
    "forced_turnovers_success_rate" DOUBLE PRECISION,
    "forced_missed_pass" BIGINT,
    "forced_missed_pass_successful" BIGINT,
    "forced_missed_pass_unsuccessful" BIGINT,
    "forced_missed_pass_success_rate" DOUBLE PRECISION,
    "forced_missed_shot" BIGINT,
    "forced_missed_shot_successful" BIGINT,
    "forced_missed_shot_unsuccessful" BIGINT,
    "forced_missed_shot_success_rate" DOUBLE PRECISION,
    "forced_lost_possession" BIGINT,
    "forced_lost_possession_successful" BIGINT,
    "forced_lost_possession_unsuccessful" BIGINT,
    "forced_lost_possession_success_rate" DOUBLE PRECISION,
    "in_shot_pass_lane" BIGINT,
    "in_shot_pass_lane_successful" BIGINT,
    "in_shot_pass_lane_unsuccessful" BIGINT,
    "in_shot_pass_lane_success_rate" DOUBLE PRECISION,
    "clearing_attempts" BIGINT,
    "clearing_attempts_successful" BIGINT,
    "clearing_attempts_unsuccessful" BIGINT,
    "clearing_attempts_success_rate" DOUBLE PRECISION,
    "penalty_kill_clears" BIGINT,
    "penalty_kill_clears_successful" BIGINT,
    "penalty_kill_clears_unsuccessful" BIGINT,
    "penalty_kill_clears_success_rate" DOUBLE PRECISION,
    "breakouts" BIGINT,
    "breakouts_successful" BIGINT,
    "breakouts_unsuccessful" BIGINT,
    "breakouts_success_rate" DOUBLE PRECISION,
    "zone_exits" BIGINT,
    "zone_exits_successful" BIGINT,
    "zone_exits_unsuccessful" BIGINT,
    "zone_exits_success_rate" DOUBLE PRECISION,
    "failed_exits" BIGINT,
    "failed_exits_successful" BIGINT,
    "failed_exits_unsuccessful" BIGINT,
    "failed_exits_success_rate" DOUBLE PRECISION,
    "attempted_breakouts" BIGINT,
    "attempted_breakouts_successful" BIGINT,
    "attempted_breakouts_unsuccessful" BIGINT,
    "attempted_breakouts_success_rate" DOUBLE PRECISION,
    "attempted_clear" BIGINT,
    "attempted_clear_successful" BIGINT,
    "attempted_clear_unsuccessful" BIGINT,
    "attempted_clear_success_rate" DOUBLE PRECISION,
    "loose_puck_wins" BIGINT,
    "loose_puck_wins_successful" BIGINT,
    "loose_puck_wins_unsuccessful" BIGINT,
    "loose_puck_wins_success_rate" DOUBLE PRECISION,
    "loose_puck_losses" BIGINT,
    "loose_puck_losses_successful" BIGINT,
    "loose_puck_losses_unsuccessful" BIGINT,
    "loose_puck_losses_success_rate" DOUBLE PRECISION,
    "puck_recoveries" BIGINT,
    "puck_recoveries_successful" BIGINT,
    "puck_recoveries_unsuccessful" BIGINT,
    "puck_recoveries_success_rate" DOUBLE PRECISION,
    "puck_retrieval_attempts" BIGINT,
    "puck_retrieval_attempts_successful" BIGINT,
    "puck_retrieval_attempts_unsuccessful" BIGINT,
    "puck_retrieval_attempts_success_rate" DOUBLE PRECISION,
    "board_battles_won" BIGINT,
    "board_battles_won_successful" BIGINT,
    "board_battles_won_unsuccessful" BIGINT,
    "board_battles_won_success_rate" DOUBLE PRECISION,
    "board_battles_lost" BIGINT,
    "board_battles_lost_successful" BIGINT,
    "board_battles_lost_unsuccessful" BIGINT,
    "board_battles_lost_success_rate" DOUBLE PRECISION,
    "puck_battles" BIGINT,
    "puck_battles_successful" BIGINT,
    "puck_battles_unsuccessful" BIGINT,
    "puck_battles_success_rate" DOUBLE PRECISION,
    "pressure" BIGINT,
    "pressure_successful" BIGINT,
    "pressure_unsuccessful" BIGINT,
    "pressure_success_rate" DOUBLE PRECISION,
    "separate_from_puck" BIGINT,
    "separate_from_puck_successful" BIGINT,
    "separate_from_puck_unsuccessful" BIGINT,
    "separate_from_puck_success_rate" DOUBLE PRECISION,
    "lost_puck" BIGINT,
    "lost_puck_successful" BIGINT,
    "lost_puck_unsuccessful" BIGINT,
    "lost_puck_success_rate" DOUBLE PRECISION,
    "misplayed_puck" BIGINT,
    "misplayed_puck_successful" BIGINT,
    "misplayed_puck_unsuccessful" BIGINT,
    "misplayed_puck_success_rate" DOUBLE PRECISION,
    "drives_total" BIGINT,
    "drives_total_successful" BIGINT,
    "drives_total_unsuccessful" BIGINT,
    "drives_total_success_rate" DOUBLE PRECISION,
    "puck_battles_total" BIGINT,
    "puck_battles_lost_total" BIGINT,
    "puck_battle_win_pct" DOUBLE PRECISION,
    "board_battle_win_pct" DOUBLE PRECISION,
    "micro_off_zone" BIGINT,
    "micro_def_zone" BIGINT,
    "micro_neutral_zone" BIGINT,
    "forecheck_intensity" BIGINT,
    "backcheck_intensity" BIGINT,
    "controlled_exits" BIGINT,
    "transition_quality" DOUBLE PRECISION,
    "plays_successful" BIGINT,
    "plays_unsuccessful" BIGINT,
    "play_success_rate" DOUBLE PRECISION,
    "possession_quality_index" DOUBLE PRECISION,
    "transition_efficiency" DOUBLE PRECISION,
    "transition_efficiency_rate" DOUBLE PRECISION,
    "pressure_index" DOUBLE PRECISION,
    "offensive_creativity_index" DOUBLE PRECISION,
    "defensive_activity_index" DOUBLE PRECISION,
    "playmaking_quality" DOUBLE PRECISION,
    "net_front_presence" DOUBLE PRECISION,
    "puck_battles_per_60" DOUBLE PRECISION,
    "xg_raw" DOUBLE PRECISION,
    "xg_for" DOUBLE PRECISION,
    "xg_flurry_adjustment" DOUBLE PRECISION,
    "shot_sequences_count" BIGINT,
    "goals_actual" BIGINT,
    "goals_above_expected" DOUBLE PRECISION,
    "xg_per_shot" DOUBLE PRECISION,
    "shots_for_xg" BIGINT,
    "finishing_skill" DOUBLE PRECISION,
    "ev_toi_seconds" BIGINT,
    "ev_cf" BIGINT,
    "ev_ca" BIGINT,
    "ev_cf_pct" DOUBLE PRECISION,
    "ev_gf" BIGINT,
    "ev_ga" BIGINT,
    "ev_goals" BIGINT,
    "ev_assists" BIGINT,
    "ev_points" BIGINT,
    "ev_shots" BIGINT,
    "pp_toi_seconds" BIGINT,
    "pp_cf" BIGINT,
    "pp_ca" BIGINT,
    "pp_cf_pct" DOUBLE PRECISION,
    "pp_gf" BIGINT,
    "pp_ga" BIGINT,
    "pp_p1_toi_seconds" BIGINT,
    "pp_p1_cf" BIGINT,
    "pp_p1_ca" BIGINT,
    "pp_p1_cf_pct" DOUBLE PRECISION,
    "pp_p1_gf" BIGINT,
    "pp_p1_ga" BIGINT,
    "pp_p2_toi_seconds" BIGINT,
    "pp_p2_cf" BIGINT,
    "pp_p2_ca" BIGINT,
    "pp_p2_cf_pct" DOUBLE PRECISION,
    "pp_p2_gf" BIGINT,
    "pp_p2_ga" BIGINT,
    "pp_p3_toi_seconds" BIGINT,
    "pp_p3_cf" BIGINT,
    "pp_p3_ca" BIGINT,
    "pp_p3_cf_pct" DOUBLE PRECISION,
    "pp_p3_gf" BIGINT,
    "pp_p3_ga" BIGINT,
    "pp_goals" BIGINT,
    "pp_assists" BIGINT,
    "pp_points" BIGINT,
    "pp_shots" BIGINT,
    "pk_toi_seconds" BIGINT,
    "pk_cf" BIGINT,
    "pk_ca" BIGINT,
    "pk_cf_pct" DOUBLE PRECISION,
    "pk_gf" BIGINT,
    "pk_ga" BIGINT,
    "pk_p1_toi_seconds" BIGINT,
    "pk_p1_cf" BIGINT,
    "pk_p1_ca" BIGINT,
    "pk_p1_cf_pct" DOUBLE PRECISION,
    "pk_p1_gf" BIGINT,
    "pk_p1_ga" BIGINT,
    "pk_p2_toi_seconds" BIGINT,
    "pk_p2_cf" BIGINT,
    "pk_p2_ca" BIGINT,
    "pk_p2_cf_pct" DOUBLE PRECISION,
    "pk_p2_gf" BIGINT,
    "pk_p2_ga" BIGINT,
    "pk_p3_toi_seconds" BIGINT,
    "pk_p3_cf" BIGINT,
    "pk_p3_ca" BIGINT,
    "pk_p3_cf_pct" DOUBLE PRECISION,
    "pk_p3_gf" BIGINT,
    "pk_p3_ga" BIGINT,
    "pk_goals" BIGINT,
    "pk_assists" BIGINT,
    "pk_points" BIGINT,
    "pk_shots" BIGINT,
    "en_toi_seconds" BIGINT,
    "en_cf" BIGINT,
    "en_ca" BIGINT,
    "en_cf_pct" DOUBLE PRECISION,
    "en_gf" BIGINT,
    "en_ga" BIGINT,
    "en_goals" BIGINT,
    "en_assists" BIGINT,
    "en_points" BIGINT,
    "en_shots" BIGINT,
    "pp_toi_pct" DOUBLE PRECISION,
    "pk_toi_pct" DOUBLE PRECISION,
    "shots_backhand" BIGINT,
    "shots_wraparound" BIGINT,
    "shots_poke" BIGINT,
    "shots_bat" BIGINT,
    "goals_wrist" BIGINT,
    "goals_one_timer" BIGINT,
    "goals_tip" BIGINT,
    "goals_backhand" BIGINT,
    "wrist_shot_pct" DOUBLE PRECISION,
    "one_timer_pct" DOUBLE PRECISION,
    "primary_shot_type" TEXT,
    "shot_type_variety" BIGINT,
    "passes_forehand" BIGINT,
    "passes_backhand" BIGINT,
    "passes_drop" BIGINT,
    "passes_lob" BIGINT,
    "passes_one_touch" BIGINT,
    "creative_passes" BIGINT,
    "passes_completed" BIGINT,
    "passes_attempted" BIGINT,
    "pass_completion_pct" DOUBLE PRECISION,
    "stretch_pass_pct" DOUBLE PRECISION,
    "pass_type_diversity" BIGINT,
    "shot_assists" BIGINT,
    "goal_creating_actions" BIGINT,
    "pre_shot_touches" BIGINT,
    "sequences_involved" BIGINT,
    "sequence_involvement_pct" DOUBLE PRECISION,
    "sog_sequences" BIGINT,
    "goal_sequences" BIGINT,
    "playmaking_index" DOUBLE PRECISION,
    "plays_under_pressure" BIGINT,
    "plays_not_pressured" BIGINT,
    "pressure_rate" DOUBLE PRECISION,
    "pressure_success_count" BIGINT,
    "pressure_success_pct" DOUBLE PRECISION,
    "unpressured_success_pct" DOUBLE PRECISION,
    "pressure_differential" DOUBLE PRECISION,
    "pressure_giveaways" BIGINT,
    "poise_index" DOUBLE PRECISION,
    "vs_elite_toi" BIGINT,
    "vs_elite_cf_pct" DOUBLE PRECISION,
    "vs_elite_gf" BIGINT,
    "vs_elite_ga" BIGINT,
    "vs_good_toi" BIGINT,
    "vs_good_cf_pct" DOUBLE PRECISION,
    "vs_good_gf" BIGINT,
    "vs_good_ga" BIGINT,
    "vs_avg_toi" BIGINT,
    "vs_avg_cf_pct" DOUBLE PRECISION,
    "vs_avg_gf" BIGINT,
    "vs_avg_ga" BIGINT,
    "vs_weak_toi" BIGINT,
    "vs_weak_cf_pct" DOUBLE PRECISION,
    "vs_weak_gf" BIGINT,
    "vs_weak_ga" BIGINT,
    "cf_pct_adjusted" DOUBLE PRECISION,
    "cf_pct_vs_expected" DOUBLE PRECISION,
    "leading_toi" BIGINT,
    "trailing_toi" BIGINT,
    "tied_toi" BIGINT,
    "close_game_toi" BIGINT,
    "leading_cf_pct" DOUBLE PRECISION,
    "trailing_cf_pct" DOUBLE PRECISION,
    "tied_cf_pct" DOUBLE PRECISION,
    "close_game_cf_pct" DOUBLE PRECISION,
    "leading_goals" BIGINT,
    "trailing_goals" BIGINT,
    "tied_goals" BIGINT,
    "p3_leading_toi" BIGINT,
    "p3_leading_cf" BIGINT,
    "p3_leading_ca" BIGINT,
    "p3_leading_cf_pct" DOUBLE PRECISION,
    "p3_leading_gf" BIGINT,
    "p3_leading_ga" BIGINT,
    "defensive_clutch_cf_pct" DOUBLE PRECISION,
    "defensive_clutch_diff" DOUBLE PRECISION,
    "unique_linemates" BIGINT,
    "top_linemate_player_id" TEXT,
    "top_linemate_toi_together" BIGINT,
    "top_line_cf_pct" DOUBLE PRECISION,
    "chemistry_score" DOUBLE PRECISION,
    "d_partner_player_id" TEXT,
    "d_partner_toi_together" BIGINT,
    "line_consistency_pct" DOUBLE PRECISION,
    "early_period_goals" BIGINT,
    "early_period_assists" BIGINT,
    "early_period_points" BIGINT,
    "early_period_shots" BIGINT,
    "late_period_goals" BIGINT,
    "late_period_assists" BIGINT,
    "late_period_points" BIGINT,
    "late_period_shots" BIGINT,
    "early_period_cf" BIGINT,
    "early_period_ca" BIGINT,
    "late_period_cf" BIGINT,
    "late_period_ca" BIGINT,
    "early_period_cf_pct" DOUBLE PRECISION,
    "late_period_cf_pct" DOUBLE PRECISION,
    "first_goal_involvement" BIGINT,
    "rebound_recoveries" BIGINT,
    "rebound_shots" BIGINT,
    "rebound_goals" BIGINT,
    "rebound_shot_pct" DOUBLE PRECISION,
    "crash_net_attempts" BIGINT,
    "crash_net_success" BIGINT,
    "garbage_goals" BIGINT,
    "game_score_raw" DOUBLE PRECISION,
    "game_score" DOUBLE PRECISION,
    "game_score_per_60" DOUBLE PRECISION,
    "gs_scoring" DOUBLE PRECISION,
    "gs_shots" DOUBLE PRECISION,
    "gs_playmaking" DOUBLE PRECISION,
    "gs_defense" DOUBLE PRECISION,
    "gs_hustle" DOUBLE PRECISION,
    "offensive_game_score" DOUBLE PRECISION,
    "defensive_game_score" DOUBLE PRECISION,
    "calculated_rating" DOUBLE PRECISION,
    "gar_offense" DOUBLE PRECISION,
    "gar_defense" DOUBLE PRECISION,
    "gar_possession" DOUBLE PRECISION,
    "gar_transition" DOUBLE PRECISION,
    "gar_poise" DOUBLE PRECISION,
    "gar_total" DOUBLE PRECISION,
    "war" DOUBLE PRECISION,
    "war_pace" DOUBLE PRECISION,
    "skill_rating" DOUBLE PRECISION,
    "expected_game_score" DOUBLE PRECISION,
    "game_score_vs_expected" DOUBLE PRECISION,
    "performance_index" DOUBLE PRECISION,
    "performance_tier" TEXT,
    "adjusted_rating" DOUBLE PRECISION,
    "rating_delta" DOUBLE PRECISION,
    "rating_vs_competition" DOUBLE PRECISION,
    "adjusted_performance_index" DOUBLE PRECISION,
    "rating_differential" DOUBLE PRECISION,
    "cf_pct_rel" DOUBLE PRECISION,
    "ff_pct_rel" DOUBLE PRECISION,
    "gf_pct" DOUBLE PRECISION,
    "gf_pct_rel" DOUBLE PRECISION,
    "goals_adj" DOUBLE PRECISION,
    "points_adj" DOUBLE PRECISION,
    "xg_adj" DOUBLE PRECISION,
    "avg_opp_rating" DOUBLE PRECISION,
    "adj_multiplier" DOUBLE PRECISION,
    "rush_def_success" DOUBLE PRECISION,
    "rush_def_success_pct" DOUBLE PRECISION,
    "rush_def_stop" DOUBLE PRECISION,
    "rush_def_stop_pct" DOUBLE PRECISION,
    "rush_def_ga" DOUBLE PRECISION,
    "puck_battles_total_successful" DOUBLE PRECISION,
    "puck_battles_total_unsuccessful" DOUBLE PRECISION,
    "puck_battles_total_success_rate" DOUBLE PRECISION,
    "puck_battles_lost_total_successful" DOUBLE PRECISION,
    "puck_battles_lost_total_unsuccessful" DOUBLE PRECISION,
    "puck_battles_lost_total_success_rate" DOUBLE PRECISION,
    "micro_off_zone_successful" DOUBLE PRECISION,
    "micro_off_zone_unsuccessful" DOUBLE PRECISION,
    "micro_off_zone_success_rate" DOUBLE PRECISION,
    "micro_def_zone_successful" DOUBLE PRECISION,
    "micro_def_zone_unsuccessful" DOUBLE PRECISION,
    "micro_def_zone_success_rate" DOUBLE PRECISION,
    "micro_neutral_zone_successful" DOUBLE PRECISION,
    "micro_neutral_zone_unsuccessful" DOUBLE PRECISION,
    "micro_neutral_zone_success_rate" DOUBLE PRECISION,
    "forecheck_intensity_successful" DOUBLE PRECISION,
    "forecheck_intensity_unsuccessful" DOUBLE PRECISION,
    "forecheck_intensity_success_rate" DOUBLE PRECISION,
    "backcheck_intensity_successful" DOUBLE PRECISION,
    "backcheck_intensity_unsuccessful" DOUBLE PRECISION,
    "backcheck_intensity_success_rate" DOUBLE PRECISION,
    "controlled_exits_successful" DOUBLE PRECISION,
    "controlled_exits_unsuccessful" DOUBLE PRECISION,
    "controlled_exits_success_rate" DOUBLE PRECISION,
    "transition_quality_successful" DOUBLE PRECISION,
    "transition_quality_unsuccessful" DOUBLE PRECISION,
    "transition_quality_success_rate" DOUBLE PRECISION,
    "plays_successful_successful" DOUBLE PRECISION,
    "plays_successful_unsuccessful" DOUBLE PRECISION,
    "plays_successful_success_rate" DOUBLE PRECISION,
    "plays_unsuccessful_successful" DOUBLE PRECISION,
    "plays_unsuccessful_unsuccessful" DOUBLE PRECISION,
    "plays_unsuccessful_success_rate" DOUBLE PRECISION,
    "play_success_rate_successful" DOUBLE PRECISION,
    "play_success_rate_unsuccessful" DOUBLE PRECISION,
    "play_success_rate_success_rate" DOUBLE PRECISION,
    "zone_exit_success_pct" DOUBLE PRECISION,
    "goals_per_60" DOUBLE PRECISION,
    "assists_per_60" DOUBLE PRECISION,
    "points_per_60" DOUBLE PRECISION,
    "shots_per_60" DOUBLE PRECISION,
    "sog_per_60" DOUBLE PRECISION,
    "dekes_per_60" DOUBLE PRECISION,
    "forechecks_per_60" DOUBLE PRECISION,
    "backchecks_per_60" DOUBLE PRECISION,
    "cycles_per_60" DOUBLE PRECISION,
    "screens_per_60" DOUBLE PRECISION,
    "poke_checks_per_60" DOUBLE PRECISION,
    "faceoffs_wdbe_per_60" DOUBLE PRECISION,
    "possession_time_offensive_zone_per_60" DOUBLE PRECISION,
    "possession_time_defensive_zone_per_60" DOUBLE PRECISION,
    "possession_time_neutral_zone_per_60" DOUBLE PRECISION,
    "possession_time_total_per_60" DOUBLE PRECISION,
    "turnovers" DOUBLE PRECISION,
    "plus_minus" BIGINT,
    "boxscore_key" TEXT
);



CREATE TABLE public."fact_player_career_stats" (
    "player_career_key" TEXT,
    "player_id" TEXT,
    "season_id" TEXT,
    "game_type" TEXT,
    "player_name" TEXT,
    "current_team" TEXT,
    "team_id" TEXT,
    "career_games" BIGINT,
    "_export_timestamp" TEXT,
    "goals" DOUBLE PRECISION,
    "primary_assists" DOUBLE PRECISION,
    "secondary_assists" DOUBLE PRECISION,
    "assists" DOUBLE PRECISION,
    "points" DOUBLE PRECISION,
    "shots" DOUBLE PRECISION,
    "sog" DOUBLE PRECISION,
    "pass_attempts" DOUBLE PRECISION,
    "pass_completed" DOUBLE PRECISION,
    "takeaways" DOUBLE PRECISION,
    "giveaways" DOUBLE PRECISION,
    "hits" DOUBLE PRECISION,
    "blocks" DOUBLE PRECISION,
    "zone_exits" DOUBLE PRECISION,
    "dump_ins" DOUBLE PRECISION,
    "fo_wins" DOUBLE PRECISION,
    "fo_losses" DOUBLE PRECISION,
    "war" DOUBLE PRECISION,
    "game_score" DOUBLE PRECISION,
    "shooting_pct" DOUBLE PRECISION,
    "pass_completion_pct" DOUBLE PRECISION,
    "faceoff_pct" DOUBLE PRECISION,
    "takeaway_giveaway_ratio" DOUBLE PRECISION,
    "position" TEXT,
    "team_name" TEXT
);

