CREATE TABLE public."fact_plays" (
    "play_key" TEXT,
    "play_id" TEXT,
    "game_id" BIGINT,
    "season_id" TEXT,
    "period" BIGINT,
    "period_id" TEXT,
    "sequence_key" TEXT,
    "first_event_key" TEXT,
    "last_event_key" TEXT,
    "event_count" BIGINT,
    "start_min" DOUBLE PRECISION,
    "start_sec" DOUBLE PRECISION,
    "duration_seconds" BIGINT,
    "video_time_start" BIGINT,
    "video_time_end" BIGINT,
    "time_bucket_id" TEXT,
    "strength_id" TEXT,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "start_zone" TEXT,
    "end_zone" TEXT,
    "start_zone_id" TEXT,
    "end_zone_id" TEXT,
    "event_types" TEXT,
    "has_goal" BOOLEAN,
    "goal_count" BIGINT,
    "has_shot" BOOLEAN,
    "shot_count" BIGINT,
    "zone_entry_count" BIGINT,
    "zone_exit_count" BIGINT,
    "pass_count" BIGINT,
    "pass_success_count" BIGINT,
    "turnover_count" BIGINT,
    "giveaway_count" BIGINT,
    "takeaway_count" BIGINT,
    "unique_player_count" BIGINT,
    "player_ids" TEXT
);