
CREATE TABLE public."fact_possession_time" (
    "possession_key" TEXT,
    "game_id" BIGINT,
    "player_id" TEXT,
    "venue" TEXT,
    "team_id" TEXT,
    "venue_id" TEXT,
    "zone_entries" BIGINT,
    "zone_exits" BIGINT,
    "ozone_entries" BIGINT,
    "dzone_entries" BIGINT,
    "possession_events" BIGINT,
    "estimated_possession_seconds" BIGINT
);


CREATE TABLE public."fact_puck_xy_long" (
    "puck_xy_key" TEXT,
    "event_id" TEXT,
    "game_id" BIGINT,
    "point_number" BIGINT,
    "x" DOUBLE PRECISION,
    "y" DOUBLE PRECISION,
    "is_start" BIGINT,
    "is_stop" BIGINT,
    "distance_to_net" DOUBLE PRECISION,
    "angle_to_net" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_puck_xy_wide" (
    "puck_xy_key" TEXT,
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "event_type" TEXT,
    "event_detail" TEXT,
    "point_count" BIGINT,
    "x_1" DOUBLE PRECISION,
    "y_1" DOUBLE PRECISION,
    "x_2" DOUBLE PRECISION,
    "y_2" DOUBLE PRECISION,
    "x_3" DOUBLE PRECISION,
    "y_3" DOUBLE PRECISION,
    "x_4" DOUBLE PRECISION,
    "y_4" DOUBLE PRECISION,
    "x_5" DOUBLE PRECISION,
    "y_5" DOUBLE PRECISION,
    "x_6" DOUBLE PRECISION,
    "y_6" DOUBLE PRECISION,
    "x_7" DOUBLE PRECISION,
    "y_7" DOUBLE PRECISION,
    "x_8" DOUBLE PRECISION,
    "y_8" DOUBLE PRECISION,
    "x_9" DOUBLE PRECISION,
    "y_9" DOUBLE PRECISION,
    "x_10" DOUBLE PRECISION,
    "y_10" DOUBLE PRECISION,
    "x_start" DOUBLE PRECISION,
    "y_start" DOUBLE PRECISION,
    "x_end" DOUBLE PRECISION,
    "y_end" DOUBLE PRECISION,
    "distance_traveled" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_registration" (
    "player_full_name" TEXT,
    "player_id" TEXT,
    "season_id" TEXT,
    "season" BIGINT,
    "restricted" TEXT,
    "email" TEXT,
    "position" TEXT,
    "norad_experience" TEXT,
    "CAF" TEXT,
    "highest_beer_league_played" TEXT,
    "skill_rating" BIGINT,
    "age" BIGINT,
    "referred_by" TEXT,
    "notes" TEXT,
    "sub_yn" TEXT,
    "drafted_team_name" TEXT,
    "drafted_team_id" TEXT,
    "player_season_registration_id" TEXT
);


CREATE TABLE public."fact_rush_events" (
    "game_id" BIGINT,
    "entry_event_id" TEXT,
    "shot_event_id" TEXT,
    "events_to_shot" BIGINT,
    "is_rush" BOOLEAN,
    "entry_type" TEXT,
    "rush_type" TEXT,
    "is_goal" BOOLEAN,
    "zone_entry_type_id" TEXT,
    "rush_key" TEXT,
    "video_time_start" BIGINT,
    "video_time_end" BIGINT
);


CREATE TABLE public."fact_rushes" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" DOUBLE PRECISION,
    "linked_event_key" TEXT,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "zone_entry_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "zone_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" DOUBLE PRECISION,
    "danger_level_id" DOUBLE PRECISION,
    "scoring_chance_key" DOUBLE PRECISION,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "time_from_entry_to_shot" DOUBLE PRECISION,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "rush_key" TEXT,
    "rush_outcome" TEXT,
    "event_supporting_player_ids" TEXT,
    "opp_supporting_player_ids" TEXT,
    "opp_player_1_id" TEXT,
    "opp_player_1_name" TEXT,
    "opp_player_1_rating" DOUBLE PRECISION,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "opp_player_3_toi" DOUBLE PRECISION,
    "opp_player_4_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION
);


CREATE TABLE public."fact_saves" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" DOUBLE PRECISION,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail_2" DOUBLE PRECISION,
    "play_detail_successful" DOUBLE PRECISION,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" DOUBLE PRECISION,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "shooter_player_id" TEXT,
    "shooter_name" TEXT,
    "shooter_rating" DOUBLE PRECISION,
    "goalie_player_id" TEXT,
    "goalie_name" TEXT,
    "goalie_rating" DOUBLE PRECISION,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "save_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" DOUBLE PRECISION,
    "danger_level_id" DOUBLE PRECISION,
    "scoring_chance_key" DOUBLE PRECISION,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "save_key" TEXT,
    "time_from_zone_entry" DOUBLE PRECISION,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "event_player_4_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "opp_player_3_toi" DOUBLE PRECISION,
    "opp_player_4_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION
);


CREATE TABLE public."fact_scoring_chances" (
    "scoring_chance_key" TEXT,
    "game_id" BIGINT,
    "event_id" TEXT,
    "period" BIGINT,
    "is_goal" BOOLEAN,
    "event_detail" TEXT,
    "event_detail_2" TEXT,
    "has_xy_data" BIGINT,
    "calculation_method" TEXT,
    "shot_distance" DOUBLE PRECISION,
    "shot_angle" DOUBLE PRECISION,
    "shot_x" DOUBLE PRECISION,
    "shot_y" DOUBLE PRECISION,
    "danger_level" TEXT,
    "is_rush" BOOLEAN,
    "is_rebound" BOOLEAN,
    "is_odd_man" BOOLEAN,
    "shot_type" TEXT,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "event_player_4_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "opp_player_3_toi" DOUBLE PRECISION,
    "opp_player_4_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION
);


CREATE TABLE public."fact_scoring_chances_detailed" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "shot_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" TEXT,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "shooter_player_id" TEXT,
    "shooter_name" TEXT,
    "shooter_rating" DOUBLE PRECISION,
    "goalie_player_id" TEXT,
    "goalie_name" TEXT,
    "goalie_rating" DOUBLE PRECISION,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "shot_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" TEXT,
    "danger_level_id" TEXT,
    "scoring_chance_key" TEXT,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "event_player_4_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "opp_player_3_toi" DOUBLE PRECISION,
    "opp_player_4_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION
);


CREATE TABLE public."fact_sequences" (
    "sequence_key" TEXT,
    "sequence_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "first_event_key" TEXT,
    "last_event_key" TEXT,
    "event_count" BIGINT,
    "start_min" DOUBLE PRECISION,
    "start_sec" DOUBLE PRECISION,
    "duration_seconds" BIGINT,
    "video_time_start" BIGINT,
    "video_time_end" BIGINT,
    "time_bucket_id" TEXT,
    "strength_id" TEXT,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "start_zone" TEXT,
    "end_zone" TEXT,
    "start_zone_id" DOUBLE PRECISION,
    "end_zone_id" DOUBLE PRECISION,
    "event_types" TEXT,
    "has_goal" BOOLEAN,
    "goal_count" BIGINT,
    "shot_count" BIGINT,
    "zone_entry_count" BIGINT,
    "zone_exit_count" BIGINT,
    "pass_count" BIGINT,
    "pass_success_count" BIGINT,
    "pass_success_rate" DOUBLE PRECISION,
    "turnover_count" BIGINT,
    "giveaway_count" BIGINT,
    "takeaway_count" BIGINT,
    "unique_player_count" BIGINT,
    "player_ids" TEXT
);


CREATE TABLE public."fact_shift_players" (
    "shift_player_id" TEXT,
    "shift_id" TEXT,
    "game_id" BIGINT,
    "shift_index" BIGINT,
    "player_game_number" BIGINT,
    "player_id" TEXT,
    "venue" TEXT,
    "position" TEXT,
    "period" BIGINT,
    "shift_duration" DOUBLE PRECISION,
    "shift_start_total_seconds" DOUBLE PRECISION,
    "shift_end_total_seconds" DOUBLE PRECISION,
    "stoppage_time" DOUBLE PRECISION,
    "playing_time" DOUBLE PRECISION,
    "running_toi_game" DOUBLE PRECISION,
    "logical_shift_number" BIGINT,
    "shift_segment" BIGINT,
    "is_first_segment" BOOLEAN,
    "is_last_segment" BOOLEAN,
    "logical_shift_duration" DOUBLE PRECISION,
    "gf" BIGINT,
    "ga" BIGINT,
    "pm" BIGINT,
    "gf_ev" BIGINT,
    "ga_ev" BIGINT,
    "gf_pp" BIGINT,
    "ga_pp" BIGINT,
    "gf_pk" BIGINT,
    "ga_pk" BIGINT,
    "pm_ev" BIGINT,
    "cf" DOUBLE PRECISION,
    "ca" DOUBLE PRECISION,
    "cf_pct" DOUBLE PRECISION,
    "ff" DOUBLE PRECISION,
    "fa" DOUBLE PRECISION,
    "ff_pct" DOUBLE PRECISION,
    "sf" DOUBLE PRECISION,
    "sa" DOUBLE PRECISION,
    "shot_diff" DOUBLE PRECISION,
    "zone_entries" DOUBLE PRECISION,
    "zone_exits" DOUBLE PRECISION,
    "giveaways" DOUBLE PRECISION,
    "takeaways" DOUBLE PRECISION,
    "fo_won" DOUBLE PRECISION,
    "fo_lost" DOUBLE PRECISION,
    "situation" TEXT,
    "situation_id" TEXT,
    "strength" TEXT,
    "strength_id" TEXT,
    "start_zone" TEXT,
    "end_zone" TEXT,
    "player_rating" DOUBLE PRECISION,
    "team_avg_rating" DOUBLE PRECISION,
    "opp_avg_rating" DOUBLE PRECISION,
    "rating_differential" DOUBLE PRECISION,
    "qoc_rating" DOUBLE PRECISION,
    "qot_rating" DOUBLE PRECISION,
    "competition_tier_id" TEXT,
    "opp_multiplier" DOUBLE PRECISION,
    "player_rating_diff" DOUBLE PRECISION,
    "expected_cf_pct" DOUBLE PRECISION,
    "cf_pct_vs_expected" DOUBLE PRECISION,
    "performance" TEXT,
    "cf_adj" DOUBLE PRECISION,
    "ca_adj" DOUBLE PRECISION,
    "cf_pct_adj" DOUBLE PRECISION,
    "team_id" TEXT,
    "opp_team_id" TEXT,
    "season_id" TEXT,
    "period_id" TEXT,
    "scf" DOUBLE PRECISION,
    "sca" DOUBLE PRECISION,
    "hdf" DOUBLE PRECISION,
    "hda" DOUBLE PRECISION,
    "event_count" DOUBLE PRECISION,
    "home_avg_rating" DOUBLE PRECISION,
    "away_avg_rating" DOUBLE PRECISION,
    "home_min_rating" DOUBLE PRECISION,
    "away_min_rating" DOUBLE PRECISION,
    "home_max_rating" DOUBLE PRECISION,
    "away_max_rating" DOUBLE PRECISION,
    "home_rating_advantage" BOOLEAN,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "game_state" TEXT,
    "score_differential" BIGINT,
    "is_close_game" BOOLEAN,
    "home_gf_all" BIGINT,
    "home_ga_all" BIGINT,
    "home_gf_ev" BIGINT,
    "home_ga_ev" BIGINT,
    "home_gf_pp" BIGINT,
    "home_ga_pp" BIGINT,
    "home_gf_pk" BIGINT,
    "home_ga_pk" BIGINT,
    "home_pm_all" BIGINT,
    "home_pm_ev" BIGINT,
    "away_gf_all" BIGINT,
    "away_ga_all" BIGINT,
    "away_gf_ev" BIGINT,
    "away_ga_ev" BIGINT,
    "away_gf_pp" BIGINT,
    "away_ga_pp" BIGINT,
    "away_gf_pk" BIGINT,
    "away_ga_pk" BIGINT,
    "away_pm_all" BIGINT,
    "away_pm_ev" BIGINT,
    "home_zone_entries" DOUBLE PRECISION,
    "away_zone_entries" DOUBLE PRECISION,
    "home_zone_exits" DOUBLE PRECISION,
    "away_zone_exits" DOUBLE PRECISION,
    "home_giveaways" DOUBLE PRECISION,
    "away_giveaways" DOUBLE PRECISION,
    "home_bad_giveaways" DOUBLE PRECISION,
    "away_bad_giveaways" DOUBLE PRECISION,
    "home_takeaways" DOUBLE PRECISION,
    "away_takeaways" DOUBLE PRECISION,
    "home_fo_won" DOUBLE PRECISION,
    "away_fo_won" DOUBLE PRECISION,
    "bad_giveaways" DOUBLE PRECISION,
    "venue_id" TEXT,
    "running_video_time" DOUBLE PRECISION,
    "shift_start_running_time" DOUBLE PRECISION,
    "shift_end_running_time" DOUBLE PRECISION,
    "shift_duration_id" TEXT
);


CREATE TABLE public."fact_shift_quality" (
    "shift_quality_key" TEXT,
    "game_id" BIGINT,
    "player_id" TEXT,
    "logical_shift_number" BIGINT,
    "shift_duration" DOUBLE PRECISION,
    "period" BIGINT,
    "quality_score" DOUBLE PRECISION,
    "shift_quality" TEXT,
    "strength" TEXT,
    "player_name" TEXT
);


CREATE TABLE public."fact_shift_quality_logical" (
    "game_id" BIGINT,
    "player_id" TEXT,
    "logical_shifts" BIGINT,
    "toi_seconds" DOUBLE PRECISION,
    "avg_quality_score" DOUBLE PRECISION,
    "player_name" TEXT,
    "player_rating" DOUBLE PRECISION,
    "avg_opp_rating" DOUBLE PRECISION,
    "gf_all" BIGINT,
    "ga_all" BIGINT,
    "cf" DOUBLE PRECISION,
    "ca" DOUBLE PRECISION,
    "pm_all" BIGINT,
    "toi_minutes" DOUBLE PRECISION,
    "cf_pct" DOUBLE PRECISION,
    "qoc" DOUBLE PRECISION,
    "expected_pm" DOUBLE PRECISION,
    "pm_vs_expected" DOUBLE PRECISION,
    "performance" TEXT
);


CREATE TABLE public."fact_shifts" (
    "shift_id" TEXT,
    "game_id" BIGINT,
    "shift_index" BIGINT,
    "period" BIGINT,
    "shift_start_type" TEXT,
    "shift_stop_type" TEXT,
    "shift_start_min" DOUBLE PRECISION,
    "shift_start_sec" DOUBLE PRECISION,
    "shift_end_min" DOUBLE PRECISION,
    "shift_end_sec" DOUBLE PRECISION,
    "home_team" TEXT,
    "away_team" TEXT,
    "home_forward_1" DOUBLE PRECISION,
    "home_forward_2" DOUBLE PRECISION,
    "home_forward_3" DOUBLE PRECISION,
    "home_defense_1" DOUBLE PRECISION,
    "home_defense_2" DOUBLE PRECISION,
    "home_xtra" DOUBLE PRECISION,
    "home_goalie" DOUBLE PRECISION,
    "away_forward_1" DOUBLE PRECISION,
    "away_forward_2" DOUBLE PRECISION,
    "away_forward_3" DOUBLE PRECISION,
    "away_defense_1" DOUBLE PRECISION,
    "away_defense_2" DOUBLE PRECISION,
    "away_xtra" DOUBLE PRECISION,
    "away_goalie" DOUBLE PRECISION,
    "shift_start_total_seconds" DOUBLE PRECISION,
    "shift_end_total_seconds" DOUBLE PRECISION,
    "shift_duration" DOUBLE PRECISION,
    "home_team_strength" DOUBLE PRECISION,
    "away_team_strength" DOUBLE PRECISION,
    "home_team_en" DOUBLE PRECISION,
    "away_team_en" DOUBLE PRECISION,
    "home_team_pk" DOUBLE PRECISION,
    "home_team_pp" DOUBLE PRECISION,
    "away_team_pp" DOUBLE PRECISION,
    "away_team_pk" DOUBLE PRECISION,
    "situation" TEXT,
    "strength" TEXT,
    "home_goals" DOUBLE PRECISION,
    "away_goals" DOUBLE PRECISION,
    "stoppage_time" DOUBLE PRECISION,
    "home_ozone_start" DOUBLE PRECISION,
    "home_ozone_end" DOUBLE PRECISION,
    "home_dzone_start" DOUBLE PRECISION,
    "home_dzone_end" DOUBLE PRECISION,
    "home_nzone_start" DOUBLE PRECISION,
    "home_nzone_end" DOUBLE PRECISION,
    "running_video_time" DOUBLE PRECISION,
    "shift_start_running_time" DOUBLE PRECISION,
    "shift_end_running_time" DOUBLE PRECISION,
    "period_start_total_running_seconds" DOUBLE PRECISION,
    "period_id" TEXT,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "season_id" TEXT,
    "time_bucket_id" TEXT,
    "strength_id" TEXT,
    "shift_start_type_derived" TEXT,
    "shift_stop_type_derived" TEXT,
    "start_zone" TEXT,
    "end_zone" TEXT,
    "start_zone_id" TEXT,
    "end_zone_id" TEXT,
    "home_forward_1_id" TEXT,
    "home_forward_2_id" TEXT,
    "home_forward_3_id" TEXT,
    "home_defense_1_id" TEXT,
    "home_defense_2_id" TEXT,
    "home_xtra_id" DOUBLE PRECISION,
    "home_goalie_id" TEXT,
    "away_forward_1_id" TEXT,
    "away_forward_2_id" TEXT,
    "away_forward_3_id" TEXT,
    "away_defense_1_id" TEXT,
    "away_defense_2_id" TEXT,
    "away_xtra_id" DOUBLE PRECISION,
    "away_goalie_id" TEXT,
    "home_avg_rating" DOUBLE PRECISION,
    "home_min_rating" DOUBLE PRECISION,
    "home_max_rating" DOUBLE PRECISION,
    "away_avg_rating" DOUBLE PRECISION,
    "away_min_rating" DOUBLE PRECISION,
    "away_max_rating" DOUBLE PRECISION,
    "rating_differential" DOUBLE PRECISION,
    "home_rating_advantage" BOOLEAN,
    "home_gf_all" BIGINT,
    "home_ga_all" BIGINT,
    "away_gf_all" BIGINT,
    "away_ga_all" BIGINT,
    "home_gf_ev" BIGINT,
    "home_ga_ev" BIGINT,
    "away_gf_ev" BIGINT,
    "away_ga_ev" BIGINT,
    "home_gf_nen" BIGINT,
    "home_ga_nen" BIGINT,
    "away_gf_nen" BIGINT,
    "away_ga_nen" BIGINT,
    "home_gf_pp" BIGINT,
    "home_ga_pp" BIGINT,
    "away_gf_pp" BIGINT,
    "away_ga_pp" BIGINT,
    "home_gf_pk" BIGINT,
    "home_ga_pk" BIGINT,
    "away_gf_pk" BIGINT,
    "away_ga_pk" BIGINT,
    "home_pm_all" BIGINT,
    "away_pm_all" BIGINT,
    "home_pm_ev" BIGINT,
    "away_pm_ev" BIGINT,
    "home_pm_nen" BIGINT,
    "away_pm_nen" BIGINT,
    "home_pm_pp" BIGINT,
    "away_pm_pp" BIGINT,
    "home_pm_pk" BIGINT,
    "away_pm_pk" BIGINT,
    "game_state" TEXT,
    "score_differential" BIGINT,
    "is_close_game" BOOLEAN,
    "sf" DOUBLE PRECISION,
    "sa" DOUBLE PRECISION,
    "shot_diff" DOUBLE PRECISION,
    "cf" DOUBLE PRECISION,
    "ca" DOUBLE PRECISION,
    "cf_pct" DOUBLE PRECISION,
    "ff" DOUBLE PRECISION,
    "fa" DOUBLE PRECISION,
    "ff_pct" DOUBLE PRECISION,
    "scf" DOUBLE PRECISION,
    "sca" DOUBLE PRECISION,
    "hdf" DOUBLE PRECISION,
    "hda" DOUBLE PRECISION,
    "home_zone_entries" DOUBLE PRECISION,
    "away_zone_entries" DOUBLE PRECISION,
    "home_zone_exits" DOUBLE PRECISION,
    "away_zone_exits" DOUBLE PRECISION,
    "home_giveaways" DOUBLE PRECISION,
    "away_giveaways" DOUBLE PRECISION,
    "home_bad_giveaways" DOUBLE PRECISION,
    "away_bad_giveaways" DOUBLE PRECISION,
    "home_takeaways" DOUBLE PRECISION,
    "away_takeaways" DOUBLE PRECISION,
    "home_fo_won" DOUBLE PRECISION,
    "away_fo_won" DOUBLE PRECISION,
    "event_count" DOUBLE PRECISION,
    "shift_start_type_id" TEXT,
    "shift_stop_type_id" TEXT,
    "situation_id" TEXT,
    "shift_key" TEXT,
    "shift_duration_id" TEXT
);


CREATE TABLE public."fact_shot_chains" (
    "chain_id" TEXT,
    "game_id" BIGINT,
    "season_id" DOUBLE PRECISION,
    "period" BIGINT,
    "entry_event_key" TEXT,
    "shot_event_key" TEXT,
    "time_to_shot" BIGINT,
    "pass_count" BIGINT,
    "events_to_shot" BIGINT,
    "touch_count" BIGINT,
    "entry_type" TEXT,
    "shot_result" TEXT,
    "is_goal" BOOLEAN,
    "team_id" TEXT,
    "team_name" TEXT,
    "home_team_id" TEXT,
    "away_team_id" TEXT,
    "home_team_name" TEXT,
    "away_team_name" TEXT,
    "event_types_chain" TEXT,
    "event_details_chain" TEXT,
    "entry_player_id" TEXT,
    "entry_player_name" TEXT,
    "shot_player_id" TEXT,
    "shot_player_name" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "zone_id" TEXT,
    "zone_entry_type_id" TEXT,
    "shot_result_detail_id" TEXT,
    "time_bucket_id" TEXT,
    "strength_id" TEXT,
    "shot_type_id" TEXT
);


CREATE TABLE public."fact_shot_danger" (
    "shot_danger_key" TEXT,
    "game_id" BIGINT,
    "event_index" TEXT,
    "is_rebound" BOOLEAN,
    "is_rush" BOOLEAN,
    "is_one_timer" BOOLEAN,
    "has_xy_data" BIGINT,
    "calculation_method" TEXT,
    "shot_distance" DOUBLE PRECISION,
    "shot_angle" DOUBLE PRECISION,
    "shot_x" DOUBLE PRECISION,
    "shot_y" DOUBLE PRECISION,
    "danger_zone" TEXT,
    "xg" DOUBLE PRECISION
);


CREATE TABLE public."fact_shot_event" (
    "shot_event_key" TEXT,
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "event_type" TEXT,
    "event_detail" TEXT,
    "is_goal" BOOLEAN,
    "shooter_player_id" TEXT,
    "shooter_name" TEXT,
    "shot_x" DOUBLE PRECISION,
    "shot_y" DOUBLE PRECISION,
    "shot_distance" DOUBLE PRECISION,
    "shot_angle" DOUBLE PRECISION,
    "friendly_screen_score" DOUBLE PRECISION,
    "own_team_screen_score" DOUBLE PRECISION,
    "total_screen_score" DOUBLE PRECISION,
    "screen_count" BIGINT,
    "is_screened" BOOLEAN,
    "net_target_x" DOUBLE PRECISION,
    "net_target_y" DOUBLE PRECISION,
    "net_location_id" DOUBLE PRECISION,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_shot_players" (
    "shot_player_key" TEXT,
    "event_id" TEXT,
    "game_id" BIGINT,
    "player_id" TEXT,
    "player_name" TEXT,
    "player_role" TEXT,
    "is_shooter_team" BOOLEAN,
    "is_shooter" BOOLEAN,
    "player_x" DOUBLE PRECISION,
    "player_y" DOUBLE PRECISION,
    "is_in_vision_cone" BOOLEAN,
    "is_in_puck_path" BOOLEAN,
    "screen_score" DOUBLE PRECISION,
    "is_screening" BOOLEAN,
    "screen_type" TEXT,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_shots" (
    "event_id" TEXT,
    "game_id" BIGINT,
    "period" BIGINT,
    "period_id" TEXT,
    "event_type" TEXT,
    "event_type_id" TEXT,
    "event_detail" TEXT,
    "event_detail_id" TEXT,
    "event_detail_2" TEXT,
    "event_detail_2_id" TEXT,
    "event_successful" TEXT,
    "event_team_zone" TEXT,
    "event_zone_id" TEXT,
    "sequence_key" TEXT,
    "play_key" TEXT,
    "tracking_event_key" TEXT,
    "shift_key" TEXT,
    "linked_event_key" DOUBLE PRECISION,
    "home_team" TEXT,
    "home_team_id" TEXT,
    "away_team" TEXT,
    "away_team_id" TEXT,
    "duration" BIGINT,
    "event_player_ids" TEXT,
    "opp_player_ids" TEXT,
    "event_start_min" DOUBLE PRECISION,
    "event_start_sec" DOUBLE PRECISION,
    "event_end_min" DOUBLE PRECISION,
    "event_end_sec" DOUBLE PRECISION,
    "time_start_total_seconds" BIGINT,
    "time_end_total_seconds" BIGINT,
    "event_running_start" BIGINT,
    "event_running_end" BIGINT,
    "running_video_time" BIGINT,
    "period_start_total_running_seconds" BIGINT,
    "running_intermission_duration" BIGINT,
    "team_venue" TEXT,
    "player_team" TEXT,
    "home_team_zone" TEXT,
    "away_team_zone" TEXT,
    "player_role" TEXT,
    "side_of_puck" TEXT,
    "role_number" BIGINT,
    "role_abrev" TEXT,
    "player_game_number" DOUBLE PRECISION,
    "strength" TEXT,
    "play_detail1" TEXT,
    "play_detail_2" TEXT,
    "play_detail_successful" TEXT,
    "pressured_pressurer" DOUBLE PRECISION,
    "puck_x_start" DOUBLE PRECISION,
    "puck_y_start" DOUBLE PRECISION,
    "is_goal" BIGINT,
    "is_highlight" BIGINT,
    "event_player_1_id_x" DOUBLE PRECISION,
    "event_player_1_name_x" DOUBLE PRECISION,
    "event_player_2_id_x" DOUBLE PRECISION,
    "event_player_2_name_x" DOUBLE PRECISION,
    "opp_player_1_id_x" DOUBLE PRECISION,
    "opp_player_1_name_x" DOUBLE PRECISION,
    "event_player_1_id_y" TEXT,
    "event_player_1_name_y" TEXT,
    "event_player_2_id_y" TEXT,
    "event_player_2_name_y" TEXT,
    "opp_player_1_id_y" TEXT,
    "opp_player_1_name_y" TEXT,
    "strength_id" TEXT,
    "shift_id" TEXT,
    "player_name" TEXT,
    "position_id" DOUBLE PRECISION,
    "shot_type_id" TEXT,
    "time_bucket_id" TEXT,
    "player_rating" DOUBLE PRECISION,
    "cycle_key" TEXT,
    "is_cycle" BIGINT,
    "is_rebound" BIGINT,
    "is_zone_entry" BIGINT,
    "is_zone_exit" BIGINT,
    "is_controlled_entry" BIGINT,
    "is_carried_entry" BIGINT,
    "is_controlled_exit" BIGINT,
    "is_carried_exit" BIGINT,
    "is_rush" BIGINT,
    "is_save" BIGINT,
    "is_sog" BIGINT,
    "is_turnover" BIGINT,
    "is_giveaway" BIGINT,
    "is_bad_giveaway" BIGINT,
    "is_takeaway" BIGINT,
    "is_faceoff" BIGINT,
    "is_penalty" BIGINT,
    "is_blocked_shot" BIGINT,
    "shooter_player_id" TEXT,
    "shooter_name" TEXT,
    "shooter_rating" DOUBLE PRECISION,
    "shot_blocker_player_id" TEXT,
    "shot_blocker_name" TEXT,
    "shot_blocker_rating" DOUBLE PRECISION,
    "goalie_player_id" TEXT,
    "goalie_name" TEXT,
    "goalie_rating" DOUBLE PRECISION,
    "is_missed_shot" BIGINT,
    "is_deflected" BIGINT,
    "is_tipped" BIGINT,
    "is_corsi" BIGINT,
    "is_fenwick" BIGINT,
    "shot_outcome_id" TEXT,
    "is_scoring_chance" BIGINT,
    "is_high_danger" BIGINT,
    "is_pressured" BIGINT,
    "danger_level" TEXT,
    "danger_level_id" TEXT,
    "scoring_chance_key" TEXT,
    "prev_event_id" TEXT,
    "prev_event_type" TEXT,
    "prev_event_detail" TEXT,
    "prev_event_team" TEXT,
    "prev_event_same_team" BIGINT,
    "next_event_id" TEXT,
    "next_event_type" TEXT,
    "next_event_detail" TEXT,
    "next_event_team" TEXT,
    "next_event_same_team" BIGINT,
    "time_since_prev" DOUBLE PRECISION,
    "time_to_next" DOUBLE PRECISION,
    "time_to_next_sog" DOUBLE PRECISION,
    "time_since_last_sog" DOUBLE PRECISION,
    "events_to_next_sog" DOUBLE PRECISION,
    "events_since_last_sog" DOUBLE PRECISION,
    "next_sog_result" TEXT,
    "led_to_sog" BIGINT,
    "is_pre_shot_event" BIGINT,
    "is_shot_assist" BIGINT,
    "time_to_next_goal" DOUBLE PRECISION,
    "time_since_last_goal" DOUBLE PRECISION,
    "events_to_next_goal" DOUBLE PRECISION,
    "events_since_last_goal" DOUBLE PRECISION,
    "led_to_goal" BIGINT,
    "time_since_zone_entry" DOUBLE PRECISION,
    "events_since_zone_entry" DOUBLE PRECISION,
    "time_since_zone_exit" DOUBLE PRECISION,
    "sequence_event_num" DOUBLE PRECISION,
    "sequence_total_events" DOUBLE PRECISION,
    "sequence_duration" DOUBLE PRECISION,
    "is_sequence_first" BIGINT,
    "is_sequence_last" BIGINT,
    "sequence_has_sog" BIGINT,
    "sequence_has_goal" BIGINT,
    "sequence_shot_count" DOUBLE PRECISION,
    "consecutive_team_events" BIGINT,
    "time_since_possession_change" DOUBLE PRECISION,
    "events_since_possession_change" DOUBLE PRECISION,
    "time_since_faceoff" DOUBLE PRECISION,
    "events_since_faceoff" DOUBLE PRECISION,
    "is_rush_calculated" BIGINT,
    "play_segment_number" DOUBLE PRECISION,
    "sequence_segment_number" DOUBLE PRECISION,
    "linked_event_segment_number" DOUBLE PRECISION,
    "time_to_next_event" DOUBLE PRECISION,
    "time_from_last_event" DOUBLE PRECISION,
    "time_to_next_goal_for" DOUBLE PRECISION,
    "time_to_next_goal_against" DOUBLE PRECISION,
    "time_from_last_goal_for" DOUBLE PRECISION,
    "time_from_last_goal_against" DOUBLE PRECISION,
    "time_to_next_stoppage" DOUBLE PRECISION,
    "time_from_last_stoppage" DOUBLE PRECISION,
    "event_player_1_toi" DOUBLE PRECISION,
    "opp_player_1_toi" DOUBLE PRECISION,
    "event_player_2_toi" DOUBLE PRECISION,
    "opp_player_2_toi" DOUBLE PRECISION,
    "event_player_3_toi" DOUBLE PRECISION,
    "opp_player_3_toi" DOUBLE PRECISION,
    "event_player_4_toi" DOUBLE PRECISION,
    "opp_player_4_toi" DOUBLE PRECISION,
    "team_on_ice_toi_avg" DOUBLE PRECISION,
    "team_on_ice_toi_min" DOUBLE PRECISION,
    "team_on_ice_toi_max" DOUBLE PRECISION,
    "opp_on_ice_toi_avg" DOUBLE PRECISION,
    "opp_on_ice_toi_min" DOUBLE PRECISION,
    "opp_on_ice_toi_max" DOUBLE PRECISION,
    "event_team_avg_rating" DOUBLE PRECISION,
    "opp_team_avg_rating" DOUBLE PRECISION,
    "rating_vs_opp" DOUBLE PRECISION,
    "shot_key" TEXT,
    "_export_timestamp" TEXT
);


CREATE TABLE public."fact_special_teams_summary" (
    "special_teams_key" TEXT,
    "team_id" TEXT,
    "games_played" BIGINT,
    "total_corsi_for" BIGINT,
    "total_corsi_against" BIGINT,
    "total_cf_pct" DOUBLE PRECISION,
    "total_xg_for" DOUBLE PRECISION
);